In [1]:
! pip install pymongo

Collecting pymongo
  Downloading pymongo-4.17.0-cp313-cp313-win_amd64.whl.metadata (10 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp313-cp313-win_amd64.whl (972 kB)
   ---------------------------------------- 0.0/972.8 kB ? eta -:--:--
   ---------------------------------------- 972.8/972.8 kB 27.3 MB/s  0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
Installing collected packages: dnspython, pymongo

   ---------------------------------------- 0/2 [dnspython]
   ---------------------------------------- 0/2 [dnspython]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   -------------------- ------------------- 1/2 [pymongo]
   ---------------------------------------- 2/2 [pymongo]

Successfully installed dnspython-2.8.0 pymongo-4.17.0

In [2]:
import pymongo
pymongo.__version__

'4.17.0'

In [3]:
# mongodb 에 연결하기
conn = pymongo.MongoClient('mongodb://admin:1234@localhost:27017')
conn

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

In [4]:
# db선택하기 (없으면 자동으로 생성됨)
db = conn.get_database("db1")
db

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'db1')

In [5]:
# 컬렉션(없으면 자동으로 생성) == 테이블
collection = db.get_collection("users")
collection

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'db1'), 'users')

In [6]:
from datetime import datetime

In [10]:


# 딕셔너리 타입으로 저장할 데이터 생성 (이메일, 암호, 이름, 나이, 등록일)
d1 = {
    "phone": "010-0000-1111",
    "email": "a", 
    "password": "a", 
    "name": "가나다", 
    "age": 23, 
    "create_at": datetime.now()
}

collection.insert_one(d1)

InsertOneResult(ObjectId('6a052df922afbaefbce22d6e'), acknowledged=True)

---

In [ ]:
import pandas as pd

df = pd.read_pickle("./pkl/customer_master.pkl")
df

In [12]:
col_customer = db.get_collection("customer_master")
# df = [{}, {}, {}]
t2 = df.to_dict(orient="records")
t2

[{'고객아이디': 'IK152942',
  '고객명': '김서준',
  '등록일시': Timestamp('2019-01-01 00:25:00'),
  '이메일': 'hirata_yuujirou@example.com',
  '성별': 'M',
  '나이': 37,
  '생년월일': Timestamp('1990-06-10 00:00:00'),
  '지역': '대전광역시',
  '년': 1990,
  '월': 6,
  '일': 10,
  '연령대': '30대'},
 {'고객아이디': 'TS808488',
  '고객명': '김예준',
  '등록일시': Timestamp('2019-01-01 01:13:00'),
  '이메일': 'tamura_shiori@example.com',
  '성별': 'F',
  '나이': 41,
  '생년월일': Timestamp('1986-05-20 00:00:00'),
  '지역': '인천광역시',
  '년': 1986,
  '월': 5,
  '일': 20,
  '연령대': '40대'},
 {'고객아이디': 'AS834628',
  '고객명': '김도윤',
  '등록일시': Timestamp('2019-01-01 02:00:00'),
  '이메일': 'hisano_yuki@example.com',
  '성별': 'F',
  '나이': 71,
  '생년월일': Timestamp('1956-01-02 00:00:00'),
  '지역': '광주광역시',
  '년': 1956,
  '월': 1,
  '일': 2,
  '연령대': '70대'},
 {'고객아이디': 'AS345469',
  '고객명': '김시우',
  '등록일시': Timestamp('2019-01-01 04:48:00'),
  '이메일': 'tsuruoka_kaoru@example.com',
  '성별': 'M',
  '나이': 82,
  '생년월일': Timestamp('1945-03-25 00:00:00'),
  '지역': '인천광역시',
  '년': 1945,
  '월': 3,
  '일': 25,
  '연령대': '80이상'},
 {'고객아이디': 'GD892565',
  '고객명': '김주원',
  '등록일시': Timestamp('2019-01-01 04:54:00'),
  '이메일': 'oouchi_takashi@example.com',
  '성별': 'M',
  '나이': 62,
  '생년월일': Timestamp('1965-08-05 00:00:00'),
  '지역': '울산광역시',
  '년': 1965,
  '월': 8,
  '일': 5,
  '연령대': '60대'},
 {'고객아이디': 'AS265381',
  '고객명': '김하준',
  '등록일시': Timestamp('2019-01-01 05:51:00'),
  '이메일': 'kasai_yousuke@example.com',
  '성별': 'M',
  '나이': 78,
  '생년월일': Timestamp('1949-08-09 00:00:00'),
  '지역': '서울특별시',
  '년': 1949,
  '월': 8,
  '일': 9,
  '연령대': '70대'},
 {'고객아이디': 'HD739338',
  '고객명': '김지호',
  '등록일시': Timestamp('2019-01-01 05:51:00'),
  '이메일': 'hashiguchi_masaya@example.com',
  '성별': 'M',
  '나이': 53,
  '생년월일': Timestamp('1974-06-04 00:00:00'),
  '지역': '대전광역시',
  '년': 1974,
  '월': 6,
  '일': 4,
  '연령대': '50대'},
 {'고객아이디': 'HI791416',
  '고객명': '김지후',
  '등록일시': Timestamp('2019-01-01 07:03:00'),
  '이메일': 'hosoi_mayuko@example.com',
  '성별': 'F',
  '나이': 38,
  '생년월일': Timestamp('1989-07-25 00:00:00'),
  '지역': '대구광역시',
  '년': 1989,
  '월': 7,
  '일': 25,
  '연령대': '30대'},
 {'고객아이디': 'HD819739',
  '고객명': '김준서',
  '등록일시': Timestamp('2019-01-01 08:17:00'),
  '이메일': 'shiomi_haruka@example.com',
  '성별': 'F',
  '나이': 58,
  '생년월일': Timestamp('1969-10-08 00:00:00'),
  '지역': '대전광역시',
  '년': 1969,
  '월': 10,
  '일': 8,
  '연령대': '50대'},
 {'고객아이디': 'OA239766',
  '고객명': '김준우',
  '등록일시': Timestamp('2019-01-01 08:59:00'),
  '이메일': 'tamaki_yukiya@example.com',
  '성별': 'M',
  '나이': 30,
  '생년월일': Timestamp('1997-01-12 00:00:00'),
  '지역': '인천광역시',
  '년': 1997,
  '월': 1,
  '일': 12,
  '연령대': '30대'},
 {'고객아이디': 'HD743252',
  '고객명': '김현우',
  '등록일시': Timestamp('2019-01-01 15:13:00'),
  '이메일': 'abe_tetsuhiro@example.com',
  '성별': 'M',
  '나이': 60,
  '생년월일': Timestamp('1967-11-08 00:00:00'),
  '지역': '서울특별시',
  '년': 1967,
  '월': 11,
  '일': 8,
  '연령대': '60대'},
 {'고객아이디': 'OA336650',
  '고객명': '김지훈',
  '등록일시': Timestamp('2019-01-01 15:57:00'),
  '이메일': 'yasuda_naoto@example.com',
  '성별': 'M',
  '나이': 77,
  '생년월일': Timestamp('1950-08-13 00:00:00'),
  '지역': '대전광역시',
  '년': 1950,
  '월': 8,
  '일': 13,
  '연령대': '70대'},
 {'고객아이디': 'OA176831',
  '고객명': '김도현',
  '등록일시': Timestamp('2019-01-01 17:30:00'),
  '이메일': 'hirayama_tomofumi@example.com',
  '성별': 'M',
  '나이': 32,
  '생년월일': Timestamp('1995-06-13 00:00:00'),
  '지역': '광주광역시',
  '년': 1995,
  '월': 6,
  '일': 13,
  '연령대': '30대'},
 {'고객아이디': 'HD104458',
  '고객명': '김건우',
  '등록일시': Timestamp('2019-01-01 19:55:00'),
  '이메일': 'kannbara_akihiro@example.com',
  '성별': 'M',
  '나이': 36,
  '생년월일': Timestamp('1991-12-18 00:00:00'),
  '지역': '인천광역시',
  '년': 1991,
  '월': 12,
  '일': 18,
  '연령대': '30대'},
 {'고객아이디': 'HI652550',
  '고객명': '김우진',
  '등록일시': Timestamp('2019-01-01 19:55:00'),
  '이메일': 'kaga_you@example.com',
  '성별': 'F',
  '나이': 51,
  '생년월일': Timestamp('1976-02-10 00:00:00'),
  '지역': '서울특별시',
  '년': 1976,
  '월': 2,
  '일': 10,
  '연령대': '50대'},
 {'고객아이디': 'HD994980',
  '고객명': '김민재',
  '등록일시': Timestamp('2019-01-01 21:22:00'),
  '이메일': 'kasai_nanase@example.com',
  '성별': 'F',
  '나이': 60,
  '생년월일': Timestamp('1967-08-05 00:00:00'),
  '지역': '울산광역시',
  '년': 1967,
  '월': 8,
  '일': 5,
  '연령대': '60대'},
 {'고객아이디': 'GD455127',
  '고객명': '김선우',
  '등록일시': Timestamp('2019-01-01 21:29:00'),
  '이메일': 'fukuyama_yoshiki@example.com',
  '성별': 'M',
  '나이': 64,
  '생년월일': Timestamp('1963-09-30 00:00:00'),
  '지역': '부산광역시',
  '년': 1963,
  '월': 9,
  '일': 30,
  '연령대': '60대'},
 {'고객아이디': 'IK623902',
  '고객명': '김현준',
  '등록일시': Timestamp('2019-01-01 21:35:00'),
  '이메일': 'fujiwara_meisa@example.com',
  '성별': 'F',
  '나이': 71,
  '생년월일': Timestamp('1956-03-31 00:00:00'),
  '지역': '서울특별시',
  '년': 1956,
  '월': 3,
  '일': 31,
  '연령대': '70대'},
 {'고객아이디': 'OA308429',
  '고객명': '김서진',
  '등록일시': Timestamp('2019-01-01 21:42:00'),
  '이메일': 'kiyota_haruka@example.com',
  '성별': 'F',
  '나이': 66,
  '생년월일': Timestamp('1961-01-23 00:00:00'),
  '지역': '부산광역시',
  '년': 1961,
  '월': 1,
  '일': 23,
  '연령대': '60대'},
 {'고객아이디': 'OA640152',
  '고객명': '김연우',
  '등록일시': Timestamp('2019-01-01 23:25:00'),
  '이메일': 'matsubara_ryou@example.com',
  '성별': 'M',
  '나이': 72,
  '생년월일': Timestamp('1955-12-18 00:00:00'),
  '지역': '광주광역시',
  '년': 1955,
  '월': 12,
  '일': 18,
  '연령대': '70대'},
 {'고객아이디': 'PL407221',
  '고객명': '김유준',
  '등록일시': Timestamp('2019-01-02 00:42:00'),
  '이메일': 'ando_erika@example.com',
  '성별': 'F',
  '나이': 79,
  '생년월일': Timestamp('1948-11-14 00:00:00'),
  '지역': '인천광역시',
  '년': 1948,
  '월': 11,
  '일': 14,
  '연령대': '70대'},
 {'고객아이디': 'AS071660',
  '고객명': '김정우',
  '등록일시': Timestamp('2019-01-02 01:25:00'),
  '이메일': 'tadokoro_hidetaka@example.com',
  '성별': 'M',
  '나이': 46,
  '생년월일': Timestamp('1981-11-18 00:00:00'),
  '지역': '울산광역시',
  '년': 1981,
  '월': 11,
  '일': 18,
  '연령대': '40대'},
 {'고객아이디': 'OA558666',
  '고객명': '김승현',
  '등록일시': Timestamp('2019-01-02 03:00:00'),
  '이메일': 'urano_aki@example.com',
  '성별': 'F',
  '나이': 70,
  '생년월일': Timestamp('1957-11-14 00:00:00'),
  '지역': '서울특별시',
  '년': 1957,
  '월': 11,
  '일': 14,
  '연령대': '70대'},
 {'고객아이디': 'OA449732',
  '고객명': '김승우',
  '등록일시': Timestamp('2019-01-02 03:27:00'),
  '이메일': 'oobayashi_suzuka@example.com',
  '성별': 'F',
  '나이': 76,
  '생년월일': Timestamp('1951-09-28 00:00:00'),
  '지역': '인천광역시',
  '년': 1951,
  '월': 9,
  '일': 28,
  '연령대': '70대'},
 {'고객아이디': 'HI531972',
  '고객명': '김준혁',
  '등록일시': Timestamp('2019-01-02 04:59:00'),
  '이메일': 'miyasako_sora@example.com',
  '성별': 'F',
  '나이': 75,
  '생년월일': Timestamp('1952-06-21 00:00:00'),
  '지역': '인천광역시',
  '년': 1952,
  '월': 6,
  '일': 21,
  '연령대': '70대'},
 {'고객아이디': 'IK661529',
  '고객명': '김지환',
  '등록일시': Timestamp('2019-01-02 05:00:00'),
  '이메일': 'kikuta_yuu@example.com',
  '성별': 'M',
  '나이': 64,
  '생년월일': Timestamp('1963-03-26 00:00:00'),
  '지역': '인천광역시',
  '년': 1963,
  '월': 3,
  '일': 26,
  '연령대': '60대'},
 {'고객아이디': 'HD176754',
  '고객명': '김시윤',
  '등록일시': Timestamp('2019-01-02 06:14:00'),
  '이메일': 'sakashita_kenji@example.com',
  '성별': 'M',
  '나이': 68,
  '생년월일': Timestamp('1959-04-07 00:00:00'),
  '지역': '서울특별시',
  '년': 1959,
  '월': 4,
  '일': 7,
  '연령대': '60대'},
 {'고객아이디': 'AS453084',
  '고객명': '김승민',
  '등록일시': Timestamp('2019-01-02 07:24:00'),
  '이메일': 'okamoto_tetsuhiro@example.com',
  '성별': 'M',
  '나이': 57,
  '생년월일': Timestamp('1970-06-17 00:00:00'),
  '지역': '서울특별시',
  '년': 1970,
  '월': 6,
  '일': 17,
  '연령대': '50대'},
 {'고객아이디': 'TS855513',
  '고객명': '김은우',
  '등록일시': Timestamp('2019-01-02 08:18:00'),
  '이메일': 'mizutani_rena@example.com',
  '성별': 'F',
  '나이': 77,
  '생년월일': Timestamp('1950-06-01 00:00:00'),
  '지역': '대구광역시',
  '년': 1950,
  '월': 6,
  '일': 1,
  '연령대': '70대'},
 {'고객아이디': 'TS971314',
  '고객명': '김지우',
  '등록일시': Timestamp('2019-01-02 09:39:00'),
  '이메일': 'ichida_yuuichi@example.com',
  '성별': 'M',
  '나이': 69,
  '생년월일': Timestamp('1958-02-06 00:00:00'),
  '지역': '부산광역시',
  '년': 1958,
  '월': 2,
  '일': 6,
  '연령대': '60대'},
 {'고객아이디': 'TS456293',
  '고객명': '김유찬',
  '등록일시': Timestamp('2019-01-02 10:41:00'),
  '이메일': 'yokoi_reina@example.com',
  '성별': 'F',
  '나이': 78,
  '생년월일': Timestamp('1949-09-15 00:00:00'),
  '지역': '부산광역시',
  '년': 1949,
  '월': 9,
  '일': 15,
  '연령대': '70대'},
 {'고객아이디': 'HI089467',
  '고객명': '김민성',
  '등록일시': Timestamp('2019-01-02 12:41:00'),
  '이메일': 'ayanokouji_kazuki@example.com',
  '성별': 'M',
  '나이': 41,
  '생년월일': Timestamp('1986-06-23 00:00:00'),
  '지역': '서울특별시',
  '년': 1986,
  '월': 6,
  '일': 23,
  '연령대': '40대'},
 {'고객아이디': 'HI499195',
  '고객명': '김준영',
  '등록일시': Timestamp('2019-01-02 15:52:00'),
  '이메일': 'watabe_yui@example.com',
  '성별': 'F',
  '나이': 51,
  '생년월일': Timestamp('1976-05-29 00:00:00'),
  '지역': '부산광역시',
  '년': 1976,
  '월': 5,
  '일': 29,
  '연령대': '50대'},
 {'고객아이디': 'OA207651',
  '고객명': '김윤우',
  '등록일시': Timestamp('2019-01-02 15:56:00'),
  '이메일': 'kanezawa_tomoka@example.com',
  '성별': 'F',
  '나이': 80,
  '생년월일': Timestamp('1947-03-01 00:00:00'),
  '지역': '울산광역시',
  '년': 1947,
  '월': 3,
  '일': 1,
  '연령대': '80이상'},
 {'고객아이디': 'AS185951',
  '고객명': '김시후',
  '등록일시': Timestamp('2019-01-02 16:54:00'),
  '이메일': 'namase_risa@example.com',
  '성별': 'F',
  '나이': 78,
  '생년월일': Timestamp('1949-07-09 00:00:00'),
  '지역': '서울특별시',
  '년': 1949,
  '월': 7,
  '일': 9,
  '연령대': '70대'},
 {'고객아이디': 'HD959899',
  '고객명': '김진우',
  '등록일시': Timestamp('2019-01-02 16:56:00'),
  '이메일': 'nakazono_tooru@example.com',
  '성별': 'M',
  '나이': 32,
  '생년월일': Timestamp('1995-05-15 00:00:00'),
  '지역': '울산광역시',
  '년': 1995,
  '월': 5,
  '일': 15,
  '연령대': '30대'},
 {'고객아이디': 'IK749861',
  '고객명': '김지원',
  '등록일시': Timestamp('2019-01-02 17:39:00'),
  '이메일': 'kodama_tooru@example.com',
  '성별': 'M',
  '나이': 80,
  '생년월일': Timestamp('1947-02-15 00:00:00'),
  '지역': '인천광역시',
  '년': 1947,
  '월': 2,
  '일': 15,
  '연령대': '80이상'},
 {'고객아이디': 'TS365803',
  '고객명': '김수현',
  '등록일시': Timestamp('2019-01-02 21:11:00'),
  '이메일': 'sugimura_mitsuru@example.com',
  '성별': 'M',
  '나이': 46,
  '생년월일': Timestamp('1981-06-18 00:00:00'),
  '지역': '대전광역시',
  '년': 1981,
  '월': 6,
  '일': 18,
  '연령대': '40대'},
 {'고객아이디': 'TS810881',
  '고객명': '김동현',
  '등록일시': Timestamp('2019-01-02 22:33:00'),
  '이메일': 'matsuoka_naoto@example.com',
  '성별': 'M',
  '나이': 33,
  '생년월일': Timestamp('1994-06-03 00:00:00'),
  '지역': '서울특별시',
  '년': 1994,
  '월': 6,
  '일': 3,
  '연령대': '30대'},
 {'고객아이디': 'IK171801',
  '고객명': '김재윤',
  '등록일시': Timestamp('2019-01-02 22:56:00'),
  '이메일': 'aoyama_kouji@example.com',
  '성별': 'M',
  '나이': 75,
  '생년월일': Timestamp('1952-08-06 00:00:00'),
  '지역': '대전광역시',
  '년': 1952,
  '월': 8,
  '일': 6,
  '연령대': '70대'},
 {'고객아이디': 'IK120435',
  '고객명': '김시현',
  '등록일시': Timestamp('2019-01-02 23:53:00'),
  '이메일': 'oomura_toshiaki@example.com',
  '성별': 'M',
  '나이': 64,
  '생년월일': Timestamp('1963-12-16 00:00:00'),
  '지역': '울산광역시',
  '년': 1963,
  '월': 12,
  '일': 16,
  '연령대': '60대'},
 {'고객아이디': 'IK077913',
  '고객명': '김민규',
  '등록일시': Timestamp('2019-01-03 00:13:00'),
  '이메일': 'toyoshima_norihito@example.com',
  '성별': 'M',
  '나이': 37,
  '생년월일': Timestamp('1990-06-05 00:00:00'),
  '지역': '대전광역시',
  '년': 1990,
  '월': 6,
  '일': 5,
  '연령대': '30대'},
 {'고객아이디': 'GD915723',
  '고객명': '김태윤',
  '등록일시': Timestamp('2019-01-03 00:14:00'),
  '이메일': 'miyawaki_waka@example.com',
  '성별': 'F',
  '나이': 35,
  '생년월일': Timestamp('1992-07-17 00:00:00'),
  '지역': '대전광역시',
  '년': 1992,
  '월': 7,
  '일': 17,
  '연령대': '30대'},
 {'고객아이디': 'HI263602',
  '고객명': '김재원',
  '등록일시': Timestamp('2019-01-03 00:41:00'),
  '이메일': 'hagiwara_masami@example.com',
  '성별': 'F',
  '나이': 68,
  '생년월일': Timestamp('1959-05-01 00:00:00'),
  '지역': '울산광역시',
  '년': 1959,
  '월': 5,
  '일': 1,
  '연령대': '60대'},
 {'고객아이디': 'PL983707',
  '고객명': '김민우',
  '등록일시': Timestamp('2019-01-03 00:53:00'),
  '이메일': 'mihashi_miri@example.com',
  '성별': 'F',
  '나이': 36,
  '생년월일': Timestamp('1991-05-31 00:00:00'),
  '지역': '서울특별시',
  '년': 1991,
  '월': 5,
  '일': 31,
  '연령대': '30대'},
 {'고객아이디': 'OA544396',
  '고객명': '김재민',
  '등록일시': Timestamp('2019-01-03 02:46:00'),
  '이메일': 'yamane_mitsunori@example.com',
  '성별': 'M',
  '나이': 38,
  '생년월일': Timestamp('1989-10-11 00:00:00'),
  '지역': '광주광역시',
  '년': 1989,
  '월': 10,
  '일': 11,
  '연령대': '30대'},
 {'고객아이디': 'PL374717',
  '고객명': '김한결',
  '등록일시': Timestamp('2019-01-03 02:57:00'),
  '이메일': 'tokuta_kenichi@example.com',
  '성별': 'M',
  '나이': 38,
  '생년월일': Timestamp('1989-04-08 00:00:00'),
  '지역': '울산광역시',
  '년': 1989,
  '월': 4,
  '일': 8,
  '연령대': '30대'},
 {'고객아이디': 'TS301045',
  '고객명': '김수호',
  '등록일시': Timestamp('2019-01-03 04:04:00'),
  '이메일': 'kiyota_haruka1@example.com',
  '성별': 'F',
  '나이': 34,
  '생년월일': Timestamp('1993-01-07 00:00:00'),
  '지역': '인천광역시',
  '년': 1993,
  '월': 1,
  '일': 7,
  '연령대': '30대'},
 {'고객아이디': 'PL400581',
  '고객명': '김은찬',
  '등록일시': Timestamp('2019-01-03 04:53:00'),
  '이메일': 'yoshioka_erika@example.com',
  '성별': 'F',
  '나이': 45,
  '생년월일': Timestamp('1982-10-27 00:00:00'),
  '지역': '서울특별시',
  '년': 1982,
  '월': 10,
  '일': 27,
  '연령대': '40대'},
 {'고객아이디': 'GD191213',
  '고객명': '김시원',
  '등록일시': Timestamp('2019-01-03 05:13:00'),
  '이메일': 'kiyono_saki@example.com',
  '성별': 'F',
  '나이': 45,
  '생년월일': Timestamp('1982-11-05 00:00:00'),
  '지역': '울산광역시',
  '년': 1982,
  '월': 11,
  '일': 5,
  '연령대': '40대'},
 {'고객아이디': 'HI988473',
  '고객명': '김윤호',
  '등록일시': Timestamp('2019-01-03 06:10:00'),
  '이메일': 'ooji_sawa@example.com',
  '성별': 'F',
  '나이': 62,
  '생년월일': Timestamp('1965-11-19 00:00:00'),
  '지역': '부산광역시',
  '년': 1965,
  '월': 11,
  '일': 19,
  '연령대': '60대'},
 {'고객아이디': 'IK779828',
  '고객명': '김민찬',
  '등록일시': Timestamp('2019-01-03 06:47:00'),
  '이메일': 'honnyama_nao@example.com',
  '성별': 'F',
  '나이': 85,
  '생년월일': Timestamp('1942-08-01 00:00:00'),
  '지역': '광주광역시',
  '년': 1942,
  '월': 8,
  '일': 1,
  '연령대': '80이상'},
 {'고객아이디': 'GD727041',
  '고객명': '김성민',
  '등록일시': Timestamp('2019-01-03 06:57:00'),
  '이메일': 'kubota_ryuuta@example.com',
  '성별': 'M',
  '나이': 55,
  '생년월일': Timestamp('1972-06-20 00:00:00'),
  '지역': '대구광역시',
  '년': 1972,
  '월': 6,
  '일': 20,
  '연령대': '50대'},
 {'고객아이디': 'HD123842',
  '고객명': '김준호',
  '등록일시': Timestamp('2019-01-03 09:20:00'),
  '이메일': 'kanzaki_keiji@example.com',
  '성별': 'M',
  '나이': 83,
  '생년월일': Timestamp('1944-11-17 00:00:00'),
  '지역': '부산광역시',
  '년': 1944,
  '월': 11,
  '일': 17,
  '연령대': '80이상'},
 {'고객아이디': 'PL534171',
  '고객명': '김승준',
  '등록일시': Timestamp('2019-01-03 09:39:00'),
  '이메일': 'nemoto_shun1@example.com',
  '성별': 'F',
  '나이': 58,
  '생년월일': Timestamp('1969-02-23 00:00:00'),
  '지역': '인천광역시',
  '년': 1969,
  '월': 2,
  '일': 23,
  '연령대': '50대'},
 {'고객아이디': 'OA368057',
  '고객명': '김성현',
  '등록일시': Timestamp('2019-01-03 09:58:00'),
  '이메일': 'matsubara_yuuichi@example.com',
  '성별': 'M',
  '나이': 43,
  '생년월일': Timestamp('1984-07-22 00:00:00'),
  '지역': '울산광역시',
  '년': 1984,
  '월': 7,
  '일': 22,
  '연령대': '40대'},
 {'고객아이디': 'IK254439',
  '고객명': '김시온',
  '등록일시': Timestamp('2019-01-03 10:24:00'),
  '이메일': 'okuno_sayaka@example.com',
  '성별': 'F',
  '나이': 29,
  '생년월일': Timestamp('1998-02-15 00:00:00'),
  '지역': '광주광역시',
  '년': 1998,
  '월': 2,
  '일': 15,
  '연령대': '20대'},
 {'고객아이디': 'PL186773',
  '고객명': '김지안',
  '등록일시': Timestamp('2019-01-03 11:20:00'),
  '이메일': 'tsukahara_mika@example.com',
  '성별': 'F',
  '나이': 30,
  '생년월일': Timestamp('1997-07-26 00:00:00'),
  '지역': '광주광역시',
  '년': 1997,
  '월': 7,
  '일': 26,
  '연령대': '30대'},
 {'고객아이디': 'OA666190',
  '고객명': '김현서',
  '등록일시': Timestamp('2019-01-03 11:28:00'),
  '이메일': 'iwasaki_kenji@example.com',
  '성별': 'M',
  '나이': 29,
  '생년월일': Timestamp('1998-05-25 00:00:00'),
  '지역': '대전광역시',
  '년': 1998,
  '월': 5,
  '일': 25,
  '연령대': '20대'},
 {'고객아이디': 'AS699883',
  '고객명': '김이준',
  '등록일시': Timestamp('2019-01-03 15:53:00'),
  '이메일': 'maki_asami@example.com',
  '성별': 'F',
  '나이': 68,
  '생년월일': Timestamp('1959-10-10 00:00:00'),
  '지역': '서울특별시',
  '년': 1959,
  '월': 10,
  '일': 10,
  '연령대': '60대'},
 {'고객아이디': 'AS569518',
  '고객명': '김재현',
  '등록일시': Timestamp('2019-01-03 16:42:00'),
  '이메일': 'kokubunn_shouko@example.com',
  '성별': 'F',
  '나이': 38,
  '생년월일': Timestamp('1989-11-15 00:00:00'),
  '지역': '인천광역시',
  '년': 1989,
  '월': 11,
  '일': 15,
  '연령대': '30대'},
 {'고객아이디': 'IK102369',
  '고객명': '김지성',
  '등록일시': Timestamp('2019-01-03 19:11:00'),
  '이메일': 'taguchi_nao@example.com',
  '성별': 'F',
  '나이': 79,
  '생년월일': Timestamp('1948-08-21 00:00:00'),
  '지역': '서울특별시',
  '년': 1948,
  '월': 8,
  '일': 21,
  '연령대': '70대'},
 {'고객아이디': 'PL470792',
  '고객명': '김태민',
  '등록일시': Timestamp('2019-01-03 22:53:00'),
  '이메일': 'kobayashi_keiko@example.com',
  '성별': 'F',
  '나이': 48,
  '생년월일': Timestamp('1979-05-21 00:00:00'),
  '지역': '광주광역시',
  '년': 1979,
  '월': 5,
  '일': 21,
  '연령대': '40대'},
 {'고객아이디': 'IK943660',
  '고객명': '김하율',
  '등록일시': Timestamp('2019-01-04 00:45:00'),
  '이메일': 'higuchi_chise@example.com',
  '성별': 'F',
  '나이': 33,
  '생년월일': Timestamp('1994-01-29 00:00:00'),
  '지역': '대구광역시',
  '년': 1994,
  '월': 1,
  '일': 29,
  '연령대': '30대'},
 {'고객아이디': 'AS450151',
  '고객명': '김예성',
  '등록일시': Timestamp('2019-01-04 00:46:00'),
  '이메일': 'oda_arata@example.com',
  '성별': 'M',
  '나이': 51,
  '생년월일': Timestamp('1976-08-08 00:00:00'),
  '지역': '대전광역시',
  '년': 1976,
  '월': 8,
  '일': 8,
  '연령대': '50대'},
 {'고객아이디': 'HD069769',
  '고객명': '김태현',
  '등록일시': Timestamp('2019-01-04 02:14:00'),
  '이메일': 'sekine_hikaru@example.com',
  '성별': 'F',
  '나이': 83,
  '생년월일': Timestamp('1944-03-03 00:00:00'),
  '지역': '인천광역시',
  '년': 1944,
  '월': 3,
  '일': 3,
  '연령대': '80이상'},
 {'고객아이디': 'TS771339',
  '고객명': '김민혁',
  '등록일시': Timestamp('2019-01-04 02:57:00'),
  '이메일': 'fukai_takahiro@example.com',
  '성별': 'M',
  '나이': 75,
  '생년월일': Timestamp('1952-10-11 00:00:00'),
  '지역': '대전광역시',
  '년': 1952,
  '월': 10,
  '일': 11,
  '연령대': '70대'},
 {'고객아이디': 'HD068817',
  '고객명': '김우빈',
  '등록일시': Timestamp('2019-01-04 03:01:00'),
  '이메일': 'hori_atsushi@example.com',
  '성별': 'M',
  '나이': 76,
  '생년월일': Timestamp('1951-05-17 00:00:00'),
  '지역': '인천광역시',
  '년': 1951,
  '월': 5,
  '일': 17,
  '연령대': '70대'},
 {'고객아이디': 'GD322464',
  '고객명': '김민호',
  '등록일시': Timestamp('2019-01-04 04:19:00'),
  '이메일': 'tamai_mitsuhiro@example.com',
  '성별': 'M',
  '나이': 52,
  '생년월일': Timestamp('1975-04-04 00:00:00'),
  '지역': '광주광역시',
  '년': 1975,
  '월': 4,
  '일': 4,
  '연령대': '50대'},
 {'고객아이디': 'HI949100',
  '고객명': '김지율',
  '등록일시': Timestamp('2019-01-04 06:35:00'),
  '이메일': 'nagashima_satoshi@example.com',
  '성별': 'M',
  '나이': 44,
  '생년월일': Timestamp('1983-05-01 00:00:00'),
  '지역': '대전광역시',
  '년': 1983,
  '월': 5,
  '일': 1,
  '연령대': '40대'},
 {'고객아이디': 'TS724794',
  '고객명': '김지한',
  '등록일시': Timestamp('2019-01-04 08:05:00'),
  '이메일': 'tomosaka_nana@example.com',
  '성별': 'F',
  '나이': 58,
  '생년월일': Timestamp('1969-06-01 00:00:00'),
  '지역': '서울특별시',
  '년': 1969,
  '월': 6,
  '일': 1,
  '연령대': '50대'},
 {'고객아이디': 'PL705609',
  '고객명': '김성준',
  '등록일시': Timestamp('2019-01-04 09:12:00'),
  '이메일': 'yamakawa_saki@example.com',
  '성별': 'F',
  '나이': 34,
  '생년월일': Timestamp('1993-09-17 00:00:00'),
  '지역': '대전광역시',
  '년': 1993,
  '월': 9,
  '일': 17,
  '연령대': '30대'},
 {'고객아이디': 'AS288339',
  '고객명': '김이안',
  '등록일시': Timestamp('2019-01-04 09:34:00'),
  '이메일': 'satou_noriko@example.com',
  '성별': 'F',
  '나이': 31,
  '생년월일': Timestamp('1996-07-13 00:00:00'),
  '지역': '부산광역시',
  '년': 1996,
  '월': 7,
  '일': 13,
  '연령대': '30대'},
 {'고객아이디': 'GD691243',
  '고객명': '김정민',
  '등록일시': Timestamp('2019-01-04 10:37:00'),
  '이메일': 'nakazono_shunji@example.com',
  '성별': 'M',
  '나이': 57,
  '생년월일': Timestamp('1970-11-20 00:00:00'),
  '지역': '인천광역시',
  '년': 1970,
  '월': 11,
  '일': 20,
  '연령대': '50대'},
 {'고객아이디': 'GD762671',
  '고객명': '김규민',
  '등록일시': Timestamp('2019-01-04 11:16:00'),
  '이메일': 'umino_emiko@example.com',
  '성별': 'F',
  '나이': 46,
  '생년월일': Timestamp('1981-10-07 00:00:00'),
  '지역': '서울특별시',
  '년': 1981,
  '월': 10,
  '일': 7,
  '연령대': '40대'},
 {'고객아이디': 'HD565792',
  '고객명': '김서우',
  '등록일시': Timestamp('2019-01-04 12:38:00'),
  '이메일': 'nakahara_ami@example.com',
  '성별': 'F',
  '나이': 83,
  '생년월일': Timestamp('1944-11-10 00:00:00'),
  '지역': '대전광역시',
  '년': 1944,
  '월': 11,
  '일': 10,
  '연령대': '80이상'},
 {'고객아이디': 'HI400734',
  '고객명': '김윤성',
  '등록일시': Timestamp('2019-01-04 13:24:00'),
  '이메일': 'shishido_akira@example.com',
  '성별': 'M',
  '나이': 72,
  '생년월일': Timestamp('1955-01-13 00:00:00'),
  '지역': '대구광역시',
  '년': 1955,
  '월': 1,
  '일': 13,
  '연령대': '70대'},
 {'고객아이디': 'AS502510',
  '고객명': '김지민',
  '등록일시': Timestamp('2019-01-04 14:38:00'),

In [13]:
col_customer.insert_many(t2)

InsertManyResult([ObjectId('6a05302022afbaefbce22d6f'), ObjectId('6a05302022afbaefbce22d70'), ObjectId('6a05302022afbaefbce22d71'), ObjectId('6a05302022afbaefbce22d72'), ObjectId('6a05302022afbaefbce22d73'), ObjectId('6a05302022afbaefbce22d74'), ObjectId('6a05302022afbaefbce22d75'), ObjectId('6a05302022afbaefbce22d76'), ObjectId('6a05302022afbaefbce22d77'), ObjectId('6a05302022afbaefbce22d78'), ObjectId('6a05302022afbaefbce22d79'), ObjectId('6a05302022afbaefbce22d7a'), ObjectId('6a05302022afbaefbce22d7b'), ObjectId('6a05302022afbaefbce22d7c'), ObjectId('6a05302022afbaefbce22d7d'), ObjectId('6a05302022afbaefbce22d7e'), ObjectId('6a05302022afbaefbce22d7f'), ObjectId('6a05302022afbaefbce22d80'), ObjectId('6a05302022afbaefbce22d81'), ObjectId('6a05302022afbaefbce22d82'), ObjectId('6a05302022afbaefbce22d83'), ObjectId('6a05302022afbaefbce22d84'), ObjectId('6a05302022afbaefbce22d85'), ObjectId('6a05302022afbaefbce22d86'), ObjectId('6a05302022afbaefbce22d87'), ObjectId('6a05302022afbaefbce22d88'), ObjectId('6a05302022afbaefbce22d89'), ObjectId('6a05302022afbaefbce22d8a'), ObjectId('6a05302022afbaefbce22d8b'), ObjectId('6a05302022afbaefbce22d8c'), ObjectId('6a05302022afbaefbce22d8d'), ObjectId('6a05302022afbaefbce22d8e'), ObjectId('6a05302022afbaefbce22d8f'), ObjectId('6a05302022afbaefbce22d90'), ObjectId('6a05302022afbaefbce22d91'), ObjectId('6a05302022afbaefbce22d92'), ObjectId('6a05302022afbaefbce22d93'), ObjectId('6a05302022afbaefbce22d94'), ObjectId('6a05302022afbaefbce22d95'), ObjectId('6a05302022afbaefbce22d96'), ObjectId('6a05302022afbaefbce22d97'), ObjectId('6a05302022afbaefbce22d98'), ObjectId('6a05302022afbaefbce22d99'), ObjectId('6a05302022afbaefbce22d9a'), ObjectId('6a05302022afbaefbce22d9b'), ObjectId('6a05302022afbaefbce22d9c'), ObjectId('6a05302022afbaefbce22d9d'), ObjectId('6a05302022afbaefbce22d9e'), ObjectId('6a05302022afbaefbce22d9f'), ObjectId('6a05302022afbaefbce22da0'), ObjectId('6a05302022afbaefbce22da1'), ObjectId('6a05302022afbaefbce22da2'), ObjectId('6a05302022afbaefbce22da3'), ObjectId('6a05302022afbaefbce22da4'), ObjectId('6a05302022afbaefbce22da5'), ObjectId('6a05302022afbaefbce22da6'), ObjectId('6a05302022afbaefbce22da7'), ObjectId('6a05302022afbaefbce22da8'), ObjectId('6a05302022afbaefbce22da9'), ObjectId('6a05302022afbaefbce22daa'), ObjectId('6a05302022afbaefbce22dab'), ObjectId('6a05302022afbaefbce22dac'), ObjectId('6a05302022afbaefbce22dad'), ObjectId('6a05302022afbaefbce22dae'), ObjectId('6a05302022afbaefbce22daf'), ObjectId('6a05302022afbaefbce22db0'), ObjectId('6a05302022afbaefbce22db1'), ObjectId('6a05302022afbaefbce22db2'), ObjectId('6a05302022afbaefbce22db3'), ObjectId('6a05302022afbaefbce22db4'), ObjectId('6a05302022afbaefbce22db5'), ObjectId('6a05302022afbaefbce22db6'), ObjectId('6a05302022afbaefbce22db7'), ObjectId('6a05302022afbaefbce22db8'), ObjectId('6a05302022afbaefbce22db9'), ObjectId('6a05302022afbaefbce22dba'), ObjectId('6a05302022afbaefbce22dbb'), ObjectId('6a05302022afbaefbce22dbc'), ObjectId('6a05302022afbaefbce22dbd'), ObjectId('6a05302022afbaefbce22dbe'), ObjectId('6a05302022afbaefbce22dbf'), ObjectId('6a05302022afbaefbce22dc0'), ObjectId('6a05302022afbaefbce22dc1'), ObjectId('6a05302022afbaefbce22dc2'), ObjectId('6a05302022afbaefbce22dc3'), ObjectId('6a05302022afbaefbce22dc4'), ObjectId('6a05302022afbaefbce22dc5'), ObjectId('6a05302022afbaefbce22dc6'), ObjectId('6a05302022afbaefbce22dc7'), ObjectId('6a05302022afbaefbce22dc8'), ObjectId('6a05302022afbaefbce22dc9'), ObjectId('6a05302022afbaefbce22dca'), ObjectId('6a05302022afbaefbce22dcb'), ObjectId('6a05302022afbaefbce22dcc'), ObjectId('6a05302022afbaefbce22dcd'), ObjectId('6a05302022afbaefbce22dce'), ObjectId('6a05302022afbaefbce22dcf'), ObjectId('6a05302022afbaefbce22dd0'), ObjectId('6a05302022afbaefbce22dd1'), ObjectId('6a05302022afbaefbce22dd2'), ObjectId('6a05302022afbaefbce22dd3'), ObjectId('6a05302022afbaefbce22dd4'), ObjectId('6a05302022afbaefbce22dd5'), ObjectId('6a05302022afbaefbce22dd6'), ObjectId('6a05302022afbaefbce22dd7'), ObjectId('6a05302022afbaefbce22dd8'), ObjectId('6a05302022afbaefbce22dd9'), ObjectId('6a05302022afbaefbce22dda'), ObjectId('6a05302022afbaefbce22ddb'), ObjectId('6a05302022afbaefbce22ddc'), ObjectId('6a05302022afbaefbce22ddd'), ObjectId('6a05302022afbaefbce22dde'), ObjectId('6a05302022afbaefbce22ddf'), ObjectId('6a05302022afbaefbce22de0'), ObjectId('6a05302022afbaefbce22de1'), ObjectId('6a05302022afbaefbce22de2'), ObjectId('6a05302022afbaefbce22de3'), ObjectId('6a05302022afbaefbce22de4'), ObjectId('6a05302022afbaefbce22de5'), ObjectId('6a05302022afbaefbce22de6'), ObjectId('6a05302022afbaefbce22de7'), ObjectId('6a05302022afbaefbce22de8'), ObjectId('6a05302022afbaefbce22de9'), ObjectId('6a05302022afbaefbce22dea'), ObjectId('6a05302022afbaefbce22deb'), ObjectId('6a05302022afbaefbce22dec'), ObjectId('6a05302022afbaefbce22ded'), ObjectId('6a05302022afbaefbce22dee'), ObjectId('6a05302022afbaefbce22def'), ObjectId('6a05302022afbaefbce22df0'), ObjectId('6a05302022afbaefbce22df1'), ObjectId('6a05302022afbaefbce22df2'), ObjectId('6a05302022afbaefbce22df3'), ObjectId('6a05302022afbaefbce22df4'), ObjectId('6a05302022afbaefbce22df5'), ObjectId('6a05302022afbaefbce22df6'), ObjectId('6a05302022afbaefbce22df7'), ObjectId('6a05302022afbaefbce22df8'), ObjectId('6a05302022afbaefbce22df9'), ObjectId('6a05302022afbaefbce22dfa'), ObjectId('6a05302022afbaefbce22dfb'), ObjectId('6a05302022afbaefbce22dfc'), ObjectId('6a05302022afbaefbce22dfd'), ObjectId('6a05302022afbaefbce22dfe'), ObjectId('6a05302022afbaefbce22dff'), ObjectId('6a05302022afbaefbce22e00'), ObjectId('6a05302022afbaefbce22e01'), ObjectId('6a05302022afbaefbce22e02'), ObjectId('6a05302022afbaefbce22e03'), ObjectId('6a05302022afbaefbce22e04'), ObjectId('6a05302022afbaefbce22e05'), ObjectId('6a05302022afbaefbce22e06'), ObjectId('6a05302022afbaefbce22e07'), ObjectId('6a05302022afbaefbce22e08'), ObjectId('6a05302022afbaefbce22e09'), ObjectId('6a05302022afbaefbce22e0a'), ObjectId('6a05302022afbaefbce22e0b'), ObjectId('6a05302022afbaefbce22e0c'), ObjectId('6a05302022afbaefbce22e0d'), ObjectId('6a05302022afbaefbce22e0e'), ObjectId('6a05302022afbaefbce22e0f'), ObjectId('6a05302022afbaefbce22e10'), ObjectId('6a05302022afbaefbce22e11'), ObjectId('6a05302022afbaefbce22e12'), ObjectId('6a05302022afbaefbce22e13'), ObjectId('6a05302022afbaefbce22e14'), ObjectId('6a05302022afbaefbce22e15'), ObjectId('6a05302022afbaefbce22e16'), ObjectId('6a05302022afbaefbce22e17'), ObjectId('6a05302022afbaefbce22e18'), ObjectId('6a05302022afbaefbce22e19'), ObjectId('6a05302022afbaefbce22e1a'), ObjectId('6a05302022afbaefbce22e1b'), ObjectId('6a05302022afbaefbce22e1c'), ObjectId('6a05302022afbaefbce22e1d'), ObjectId('6a05302022afbaefbce22e1e'), ObjectId('6a05302022afbaefbce22e1f'), ObjectId('6a05302022afbaefbce22e20'), ObjectId('6a05302022afbaefbce22e21'), ObjectId('6a05302022afbaefbce22e22'), ObjectId('6a05302022afbaefbce22e23'), ObjectId('6a05302022afbaefbce22e24'), ObjectId('6a05302022afbaefbce22e25'), ObjectId('6a05302022afbaefbce22e26'), ObjectId('6a05302022afbaefbce22e27'), ObjectId('6a05302022afbaefbce22e28'), ObjectId('6a05302022afbaefbce22e29'), ObjectId('6a05302022afbaefbce22e2a'), ObjectId('6a05302022afbaefbce22e2b'), ObjectId('6a05302022afbaefbce22e2c'), ObjectId('6a05302022afbaefbce22e2d'), ObjectId('6a05302022afbaefbce22e2e'), ObjectId('6a05302022afbaefbce22e2f'), ObjectId('6a05302022afbaefbce22e30'), ObjectId('6a05302022afbaefbce22e31'), ObjectId('6a05302022afbaefbce22e32'), ObjectId('6a05302022afbaefbce22e33'), ObjectId('6a05302022afbaefbce22e34'), ObjectId('6a05302022afbaefbce22e35'), ObjectId('6a05302022afbaefbce22e36'), ObjectId('6a05302022afbaefbce22e37'), ObjectId('6a05302022afbaefbce22e38'), ObjectId('6a05302022afbaefbce22e39'), ObjectId('6a05302022afbaefbce22e3a'), ObjectId('6a05302022afbaefbce22e3b'), ObjectId('6a05302022afbaefbce22e3c'), ObjectId('6a05302022afbaefbce22e3d'), ObjectId('6a05302022afbaefbce22e3e'), ObjectId('6a05302022afbaefbce22e3f'), ObjectId('6a05302022afbaefbce22e40'), ObjectId('6a05302022afbaefbce22e41'), ObjectId('6a05302022afbaefbce22e42'), ObjectId('6a05302022afbaefbce22e43'), ObjectId('6a05302022afbaefbce22e44'), ObjectId('6a05302022afbaefbce22e45'), ObjectId('6a05302022afbaefbce22e46'), ObjectId('6a05302022afbaefbce22e47'), ObjectId('6a05302022afbaefbce22e48'), ObjectId('6a05302022afbaefbce22e49'), ObjectId('6a05302022afbaefbce22e4a'), ObjectId('6a05302022afbaefbce22e4b'), ObjectId('6a05302022afbaefbce22e4c'), ObjectId('6a05302022afbaefbce22e4d'), ObjectId('6a05302022afbaefbce22e4e'), ObjectId('6a05302022afbaefbce22e4f'), ObjectId('6a05302022afbaefbce22e50'), ObjectId('6a05302022afbaefbce22e51'), ObjectId('6a05302022afbaefbce22e52'), ObjectId('6a05302022afbaefbce22e53'), ObjectId('6a05302022afbaefbce22e54'), ObjectId('6a05302022afbaefbce22e55'), ObjectId('6a05302022afbaefbce22e56'), ObjectId('6a05302022afbaefbce22e57'), ObjectId('6a05302022afbaefbce22e58'), ObjectId('6a05302022afbaefbce22e59'), ObjectId('6a05302022afbaefbce22e5a'), ObjectId('6a05302022afbaefbce22e5b'), ObjectId('6a05302022afbaefbce22e5c'), ObjectId('6a05302022afbaefbce22e5d'), ObjectId('6a05302022afbaefbce22e5e'), ObjectId('6a05302022afbaefbce22e5f'), ObjectId('6a05302022afbaefbce22e60'), ObjectId('6a05302022afbaefbce22e61'), ObjectId('6a05302022afbaefbce22e62'), ObjectId('6a05302022afbaefbce22e63'), ObjectId('6a05302022afbaefbce22e64'), ObjectId('6a05302022afbaefbce22e65'), ObjectId('6a05302022afbaefbce22e66'), ObjectId('6a05302022afbaefbce22e67'), ObjectId('6a05302022afbaefbce22e68'), ObjectId('6a05302022afbaefbce22e69'), ObjectId('6a05302022afbaefbce22e6a'), ObjectId('6a05302022afbaefbce22e6b'), ObjectId('6a05302022afbaefbce22e6c'), ObjectId('6a05302022afbaefbce22e6d'), ObjectId('6a05302022afbaefbce22e6e'), ObjectId('6a05302022afbaefbce22e6f'), ObjectId('6a05302022afbaefbce22e70'), ObjectId('6a05302022afbaefbce22e71'), ObjectId('6a05302022afbaefbce22e72'), ObjectId('6a05302022afbaefbce22e73'), ObjectId('6a05302022afbaefbce22e74'), ObjectId('6a05302022afbaefbce22e75'), ObjectId('6a05302022afbaefbce22e76'), ObjectId('6a05302022afbaefbce22e77'), ObjectId('6a05302022afbaefbce22e78'), ObjectId('6a05302022afbaefbce22e79'), ObjectId('6a05302022afbaefbce22e7a'), ObjectId('6a05302022afbaefbce22e7b'), ObjectId('6a05302022afbaefbce22e7c'), ObjectId('6a05302022afbaefbce22e7d'), ObjectId('6a05302022afbaefbce22e7e'), ObjectId('6a05302022afbaefbce22e7f'), ObjectId('6a05302022afbaefbce22e80'), ObjectId('6a05302022afbaefbce22e81'), ObjectId('6a05302022afbaefbce22e82'), ObjectId('6a05302022afbaefbce22e83'), ObjectId('6a05302022afbaefbce22e84'), ObjectId('6a05302022afbaefbce22e85'), ObjectId('6a05302022afbaefbce22e86'), ObjectId('6a05302022afbaefbce22e87'), ObjectId('6a05302022afbaefbce22e88'), ObjectId('6a05302022afbaefbce22e89'), ObjectId('6a05302022afbaefbce22e8a'), ObjectId('6a05302022afbaefbce22e8b'), ObjectId('6a05302022afbaefbce22e8c'), ObjectId('6a05302022afbaefbce22e8d'), ObjectId('6a05302022afbaefbce22e8e'), ObjectId('6a05302022afbaefbce22e8f'), ObjectId('6a05302022afbaefbce22e90'), ObjectId('6a05302022afbaefbce22e91'), ObjectId('6a05302022afbaefbce22e92'), ObjectId('6a05302022afbaefbce22e93'), ObjectId('6a05302022afbaefbce22e94'), ObjectId('6a05302022afbaefbce22e95'), ObjectId('6a05302022afbaefbce22e96'), ObjectId('6a05302022afbaefbce22e97'), ObjectId('6a05302022afbaefbce22e98'), ObjectId('6a05302022afbaefbce22e99'), ObjectId('6a05302022afbaefbce22e9a'), ObjectId('6a05302022afbaefbce22e9b'), ObjectId('6a05302022afbaefbce22e9c'), ObjectId('6a05302022afbaefbce22e9d'), ObjectId('6a05302022afbaefbce22e9e'), ObjectId('6a05302022afbaefbce22e9f'), ObjectId('6a05302022afbaefbce22ea0'), ObjectId('6a05302022afbaefbce22ea1'), ObjectId('6a05302022afbaefbce22ea2'), ObjectId('6a05302022afbaefbce22ea3'), ObjectId('6a05302022afbaefbce22ea4'), ObjectId('6a05302022afbaefbce22ea5'), ObjectId('6a05302022afbaefbce22ea6'), ObjectId('6a05302022afbaefbce22ea7'), ObjectId('6a05302022afbaefbce22ea8'), ObjectId('6a05302022afbaefbce22ea9'), ObjectId('6a05302022afbaefbce22eaa'), ObjectId('6a05302022afbaefbce22eab'), ObjectId('6a05302022afbaefbce22eac'), ObjectId('6a05302022afbaefbce22ead'), ObjectId('6a05302022afbaefbce22eae'), ObjectId('6a05302022afbaefbce22eaf'), ObjectId('6a05302022afbaefbce22eb0'), ObjectId('6a05302022afbaefbce22eb1'), ObjectId('6a05302022afbaefbce22eb2'), ObjectId('6a05302022afbaefbce22eb3'), ObjectId('6a05302022afbaefbce22eb4'), ObjectId('6a05302022afbaefbce22eb5'), ObjectId('6a05302022afbaefbce22eb6'), ObjectId('6a05302022afbaefbce22eb7'), ObjectId('6a05302022afbaefbce22eb8'), ObjectId('6a05302022afbaefbce22eb9'), ObjectId('6a05302022afbaefbce22eba'), ObjectId('6a05302022afbaefbce22ebb'), ObjectId('6a05302022afbaefbce22ebc'), ObjectId('6a05302022afbaefbce22ebd'), ObjectId('6a05302022afbaefbce22ebe'), ObjectId('6a05302022afbaefbce22ebf'), ObjectId('6a05302022afbaefbce22ec0'), ObjectId('6a05302022afbaefbce22ec1'), ObjectId('6a05302022afbaefbce22ec2'), ObjectId('6a05302022afbaefbce22ec3'), ObjectId('6a05302022afbaefbce22ec4'), ObjectId('6a05302022afbaefbce22ec5'), ObjectId('6a05302022afbaefbce22ec6'), ObjectId('6a05302022afbaefbce22ec7'), ObjectId('6a05302022afbaefbce22ec8'), ObjectId('6a05302022afbaefbce22ec9'), ObjectId('6a05302022afbaefbce22eca'), ObjectId('6a05302022afbaefbce22ecb'), ObjectId('6a05302022afbaefbce22ecc'), ObjectId('6a05302022afbaefbce22ecd'), ObjectId('6a05302022afbaefbce22ece'), ObjectId('6a05302022afbaefbce22ecf'), ObjectId('6a05302022afbaefbce22ed0'), ObjectId('6a05302022afbaefbce22ed1'), ObjectId('6a05302022afbaefbce22ed2'), ObjectId('6a05302022afbaefbce22ed3'), ObjectId('6a05302022afbaefbce22ed4'), ObjectId('6a05302022afbaefbce22ed5'), ObjectId('6a05302022afbaefbce22ed6'), ObjectId('6a05302022afbaefbce22ed7'), ObjectId('6a05302022afbaefbce22ed8'), ObjectId('6a05302022afbaefbce22ed9'), ObjectId('6a05302022afbaefbce22eda'), ObjectId('6a05302022afbaefbce22edb'), ObjectId('6a05302022afbaefbce22edc'), ObjectId('6a05302022afbaefbce22edd'), ObjectId('6a05302022afbaefbce22ede'), ObjectId('6a05302022afbaefbce22edf'), ObjectId('6a05302022afbaefbce22ee0'), ObjectId('6a05302022afbaefbce22ee1'), ObjectId('6a05302022afbaefbce22ee2'), ObjectId('6a05302022afbaefbce22ee3'), ObjectId('6a05302022afbaefbce22ee4'), ObjectId('6a05302022afbaefbce22ee5'), ObjectId('6a05302022afbaefbce22ee6'), ObjectId('6a05302022afbaefbce22ee7'), ObjectId('6a05302022afbaefbce22ee8'), ObjectId('6a05302022afbaefbce22ee9'), ObjectId('6a05302022afbaefbce22eea'), ObjectId('6a05302022afbaefbce22eeb'), ObjectId('6a05302022afbaefbce22eec'), ObjectId('6a05302022afbaefbce22eed'), ObjectId('6a05302022afbaefbce22eee'), ObjectId('6a05302022afbaefbce22eef'), ObjectId('6a05302022afbaefbce22ef0'), ObjectId('6a05302022afbaefbce22ef1'), ObjectId('6a05302022afbaefbce22ef2'), ObjectId('6a05302022afbaefbce22ef3'), ObjectId('6a05302022afbaefbce22ef4'), ObjectId('6a05302022afbaefbce22ef5'), ObjectId('6a05302022afbaefbce22ef6'), ObjectId('6a05302022afbaefbce22ef7'), ObjectId('6a05302022afbaefbce22ef8'), ObjectId('6a05302022afbaefbce22ef9'), ObjectId('6a05302022afbaefbce22efa'), ObjectId('6a05302022afbaefbce22efb'), ObjectId('6a05302022afbaefbce22efc'), ObjectId('6a05302022afbaefbce22efd'), ObjectId('6a05302022afbaefbce22efe'), ObjectId('6a05302022afbaefbce22eff'), ObjectId('6a05302022afbaefbce22f00'), ObjectId('6a05302022afbaefbce22f01'), ObjectId('6a05302022afbaefbce22f02'), ObjectId('6a05302022afbaefbce22f03'), ObjectId('6a05302022afbaefbce22f04'), ObjectId('6a05302022afbaefbce22f05'), ObjectId('6a05302022afbaefbce22f06'), ObjectId('6a05302022afbaefbce22f07'), ObjectId('6a05302022afbaefbce22f08'), ObjectId('6a05302022afbaefbce22f09'), ObjectId('6a05302022afbaefbce22f0a'), ObjectId('6a05302022afbaefbce22f0b'), ObjectId('6a05302022afbaefbce22f0c'), ObjectId('6a05302022afbaefbce22f0d'), ObjectId('6a05302022afbaefbce22f0e'), ObjectId('6a05302022afbaefbce22f0f'), ObjectId('6a05302022afbaefbce22f10'), ObjectId('6a05302022afbaefbce22f11'), ObjectId('6a05302022afbaefbce22f12'), ObjectId('6a05302022afbaefbce22f13'), ObjectId('6a05302022afbaefbce22f14'), ObjectId('6a05302022afbaefbce22f15'), ObjectId('6a05302022afbaefbce22f16'), ObjectId('6a05302022afbaefbce22f17'), ObjectId('6a05302022afbaefbce22f18'), ObjectId('6a05302022afbaefbce22f19'), ObjectId('6a05302022afbaefbce22f1a'), ObjectId('6a05302022afbaefbce22f1b'), ObjectId('6a05302022afbaefbce22f1c'), ObjectId('6a05302022afbaefbce22f1d'), ObjectId('6a05302022afbaefbce22f1e'), ObjectId('6a05302022afbaefbce22f1f'), ObjectId('6a05302022afbaefbce22f20'), ObjectId('6a05302022afbaefbce22f21'), ObjectId('6a05302022afbaefbce22f22'), ObjectId('6a05302022afbaefbce22f23'), ObjectId('6a05302022afbaefbce22f24'), ObjectId('6a05302022afbaefbce22f25'), ObjectId('6a05302022afbaefbce22f26'), ObjectId('6a05302022afbaefbce22f27'), ObjectId('6a05302022afbaefbce22f28'), ObjectId('6a05302022afbaefbce22f29'), ObjectId('6a05302022afbaefbce22f2a'), ObjectId('6a05302022afbaefbce22f2b'), ObjectId('6a05302022afbaefbce22f2c'), ObjectId('6a05302022afbaefbce22f2d'), ObjectId('6a05302022afbaefbce22f2e'), ObjectId('6a05302022afbaefbce22f2f'), ObjectId('6a05302022afbaefbce22f30'), ObjectId('6a05302022afbaefbce22f31'), ObjectId('6a05302022afbaefbce22f32'), ObjectId('6a05302022afbaefbce22f33'), ObjectId('6a05302022afbaefbce22f34'), ObjectId('6a05302022afbaefbce22f35'), ObjectId('6a05302022afbaefbce22f36'), ObjectId('6a05302022afbaefbce22f37'), ObjectId('6a05302022afbaefbce22f38'), ObjectId('6a05302022afbaefbce22f39'), ObjectId('6a05302022afbaefbce22f3a'), ObjectId('6a05302022afbaefbce22f3b'), ObjectId('6a05302022afbaefbce22f3c'), ObjectId('6a05302022afbaefbce22f3d'), ObjectId('6a05302022afbaefbce22f3e'), ObjectId('6a05302022afbaefbce22f3f'), ObjectId('6a05302022afbaefbce22f40'), ObjectId('6a05302022afbaefbce22f41'), ObjectId('6a05302022afbaefbce22f42'), ObjectId('6a05302022afbaefbce22f43'), ObjectId('6a05302022afbaefbce22f44'), ObjectId('6a05302022afbaefbce22f45'), ObjectId('6a05302022afbaefbce22f46'), ObjectId('6a05302022afbaefbce22f47'), ObjectId('6a05302022afbaefbce22f48'), ObjectId('6a05302022afbaefbce22f49'), ObjectId('6a05302022afbaefbce22f4a'), ObjectId('6a05302022afbaefbce22f4b'), ObjectId('6a05302022afbaefbce22f4c'), ObjectId('6a05302022afbaefbce22f4d'), ObjectId('6a05302022afbaefbce22f4e'), ObjectId('6a05302022afbaefbce22f4f'), ObjectId('6a05302022afbaefbce22f50'), ObjectId('6a05302022afbaefbce22f51'), ObjectId('6a05302022afbaefbce22f52'), ObjectId('6a05302022afbaefbce22f53'), ObjectId('6a05302022afbaefbce22f54'), ObjectId('6a05302022afbaefbce22f55'), ObjectId('6a05302022afbaefbce22f56'), ObjectId('6a05302022afbaefbce22f57'), ObjectId('6a05302022afbaefbce22f58'), ObjectId('6a05302022afbaefbce22f59'), ObjectId('6a05302022afbaefbce22f5a'), ObjectId('6a05302022afbaefbce22f5b'), ObjectId('6a05302022afbaefbce22f5c'), ObjectId('6a05302022afbaefbce22f5d'), ObjectId('6a05302022afbaefbce22f5e'), ObjectId('6a05302022afbaefbce22f5f'), ObjectId('6a05302022afbaefbce22f60'), ObjectId('6a05302022afbaefbce22f61'), ObjectId('6a05302022afbaefbce22f62'), ObjectId('6a05302022afbaefbce22f63'), ObjectId('6a05302022afbaefbce22f64'), ObjectId('6a05302022afbaefbce22f65'), ObjectId('6a05302022afbaefbce22f66'), ObjectId('6a05302022afbaefbce22f67'), ObjectId('6a05302022afbaefbce22f68'), ObjectId('6a05302022afbaefbce22f69'), ObjectId('6a05302022afbaefbce22f6a'), ObjectId('6a05302022afbaefbce22f6b'), ObjectId('6a05302022afbaefbce22f6c'), ObjectId('6a05302022afbaefbce22f6d'), ObjectId('6a05302022afbaefbce22f6e'), ObjectId('6a05302022afbaefbce22f6f'), ObjectId('6a05302022afbaefbce22f70'), ObjectId('6a05302022afbaefbce22f71'), ObjectId('6a05302022afbaefbce22f72'), ObjectId('6a05302022afbaefbce22f73'), ObjectId('6a05302022afbaefbce22f74'), ObjectId('6a05302022afbaefbce22f75'), ObjectId('6a05302022afbaefbce22f76'), ObjectId('6a05302022afbaefbce22f77'), ObjectId('6a05302022afbaefbce22f78'), ObjectId('6a05302022afbaefbce22f79'), ObjectId('6a05302022afbaefbce22f7a'), ObjectId('6a05302022afbaefbce22f7b'), ObjectId('6a05302022afbaefbce22f

In [14]:
df = pd.read_pickle("./pkl/item_master.pkl")
col = db.get_collection("item_master")
t3 = df.to_dict(orient="records")
col.insert_many(t3)

InsertManyResult([ObjectId('6a05313f22afbaefbce240f7'), ObjectId('6a05313f22afbaefbce240f8'), ObjectId('6a05313f22afbaefbce240f9'), ObjectId('6a05313f22afbaefbce240fa'), ObjectId('6a05313f22afbaefbce240fb')], acknowledged=True)

In [15]:
df = pd.read_pickle("./pkl/transaction_master.pkl")
col = db.get_collection("transaction_master")
t4 = df.to_dict(orient="records")
col.insert_many(t4)

InsertManyResult([ObjectId('6a05318b22afbaefbce240fc'), ObjectId('6a05318b22afbaefbce240fd'), ObjectId('6a05318b22afbaefbce240fe'), ObjectId('6a05318b22afbaefbce240ff'), ObjectId('6a05318b22afbaefbce24100'), ObjectId('6a05318b22afbaefbce24101'), ObjectId('6a05318b22afbaefbce24102'), ObjectId('6a05318b22afbaefbce24103'), ObjectId('6a05318b22afbaefbce24104'), ObjectId('6a05318b22afbaefbce24105'), ObjectId('6a05318b22afbaefbce24106'), ObjectId('6a05318b22afbaefbce24107'), ObjectId('6a05318b22afbaefbce24108'), ObjectId('6a05318b22afbaefbce24109'), ObjectId('6a05318b22afbaefbce2410a'), ObjectId('6a05318b22afbaefbce2410b'), ObjectId('6a05318b22afbaefbce2410c'), ObjectId('6a05318b22afbaefbce2410d'), ObjectId('6a05318b22afbaefbce2410e'), ObjectId('6a05318b22afbaefbce2410f'), ObjectId('6a05318b22afbaefbce24110'), ObjectId('6a05318b22afbaefbce24111'), ObjectId('6a05318b22afbaefbce24112'), ObjectId('6a05318b22afbaefbce24113'), ObjectId('6a05318b22afbaefbce24114'), ObjectId('6a05318b22afbaefbce24115'), ObjectId('6a05318b22afbaefbce24116'), ObjectId('6a05318b22afbaefbce24117'), ObjectId('6a05318b22afbaefbce24118'), ObjectId('6a05318b22afbaefbce24119'), ObjectId('6a05318b22afbaefbce2411a'), ObjectId('6a05318b22afbaefbce2411b'), ObjectId('6a05318b22afbaefbce2411c'), ObjectId('6a05318b22afbaefbce2411d'), ObjectId('6a05318b22afbaefbce2411e'), ObjectId('6a05318b22afbaefbce2411f'), ObjectId('6a05318b22afbaefbce24120'), ObjectId('6a05318b22afbaefbce24121'), ObjectId('6a05318b22afbaefbce24122'), ObjectId('6a05318b22afbaefbce24123'), ObjectId('6a05318b22afbaefbce24124'), ObjectId('6a05318b22afbaefbce24125'), ObjectId('6a05318b22afbaefbce24126'), ObjectId('6a05318b22afbaefbce24127'), ObjectId('6a05318b22afbaefbce24128'), ObjectId('6a05318b22afbaefbce24129'), ObjectId('6a05318b22afbaefbce2412a'), ObjectId('6a05318b22afbaefbce2412b'), ObjectId('6a05318b22afbaefbce2412c'), ObjectId('6a05318b22afbaefbce2412d'), ObjectId('6a05318b22afbaefbce2412e'), ObjectId('6a05318b22afbaefbce2412f'), ObjectId('6a05318b22afbaefbce24130'), ObjectId('6a05318b22afbaefbce24131'), ObjectId('6a05318b22afbaefbce24132'), ObjectId('6a05318b22afbaefbce24133'), ObjectId('6a05318b22afbaefbce24134'), ObjectId('6a05318b22afbaefbce24135'), ObjectId('6a05318b22afbaefbce24136'), ObjectId('6a05318b22afbaefbce24137'), ObjectId('6a05318b22afbaefbce24138'), ObjectId('6a05318b22afbaefbce24139'), ObjectId('6a05318b22afbaefbce2413a'), ObjectId('6a05318b22afbaefbce2413b'), ObjectId('6a05318b22afbaefbce2413c'), ObjectId('6a05318b22afbaefbce2413d'), ObjectId('6a05318b22afbaefbce2413e'), ObjectId('6a05318b22afbaefbce2413f'), ObjectId('6a05318b22afbaefbce24140'), ObjectId('6a05318b22afbaefbce24141'), ObjectId('6a05318b22afbaefbce24142'), ObjectId('6a05318b22afbaefbce24143'), ObjectId('6a05318b22afbaefbce24144'), ObjectId('6a05318b22afbaefbce24145'), ObjectId('6a05318b22afbaefbce24146'), ObjectId('6a05318b22afbaefbce24147'), ObjectId('6a05318b22afbaefbce24148'), ObjectId('6a05318b22afbaefbce24149'), ObjectId('6a05318b22afbaefbce2414a'), ObjectId('6a05318b22afbaefbce2414b'), ObjectId('6a05318b22afbaefbce2414c'), ObjectId('6a05318b22afbaefbce2414d'), ObjectId('6a05318b22afbaefbce2414e'), ObjectId('6a05318b22afbaefbce2414f'), ObjectId('6a05318b22afbaefbce24150'), ObjectId('6a05318b22afbaefbce24151'), ObjectId('6a05318b22afbaefbce24152'), ObjectId('6a05318b22afbaefbce24153'), ObjectId('6a05318b22afbaefbce24154'), ObjectId('6a05318b22afbaefbce24155'), ObjectId('6a05318b22afbaefbce24156'), ObjectId('6a05318b22afbaefbce24157'), ObjectId('6a05318b22afbaefbce24158'), ObjectId('6a05318b22afbaefbce24159'), ObjectId('6a05318b22afbaefbce2415a'), ObjectId('6a05318b22afbaefbce2415b'), ObjectId('6a05318b22afbaefbce2415c'), ObjectId('6a05318b22afbaefbce2415d'), ObjectId('6a05318b22afbaefbce2415e'), ObjectId('6a05318b22afbaefbce2415f'), ObjectId('6a05318b22afbaefbce24160'), ObjectId('6a05318b22afbaefbce24161'), ObjectId('6a05318b22afbaefbce24162'), ObjectId('6a05318b22afbaefbce24163'), ObjectId('6a05318b22afbaefbce24164'), ObjectId('6a05318b22afbaefbce24165'), ObjectId('6a05318b22afbaefbce24166'), ObjectId('6a05318b22afbaefbce24167'), ObjectId('6a05318b22afbaefbce24168'), ObjectId('6a05318b22afbaefbce24169'), ObjectId('6a05318b22afbaefbce2416a'), ObjectId('6a05318b22afbaefbce2416b'), ObjectId('6a05318b22afbaefbce2416c'), ObjectId('6a05318b22afbaefbce2416d'), ObjectId('6a05318b22afbaefbce2416e'), ObjectId('6a05318b22afbaefbce2416f'), ObjectId('6a05318b22afbaefbce24170'), ObjectId('6a05318b22afbaefbce24171'), ObjectId('6a05318b22afbaefbce24172'), ObjectId('6a05318b22afbaefbce24173'), ObjectId('6a05318b22afbaefbce24174'), ObjectId('6a05318b22afbaefbce24175'), ObjectId('6a05318b22afbaefbce24176'), ObjectId('6a05318b22afbaefbce24177'), ObjectId('6a05318b22afbaefbce24178'), ObjectId('6a05318b22afbaefbce24179'), ObjectId('6a05318b22afbaefbce2417a'), ObjectId('6a05318b22afbaefbce2417b'), ObjectId('6a05318b22afbaefbce2417c'), ObjectId('6a05318b22afbaefbce2417d'), ObjectId('6a05318b22afbaefbce2417e'), ObjectId('6a05318b22afbaefbce2417f'), ObjectId('6a05318b22afbaefbce24180'), ObjectId('6a05318b22afbaefbce24181'), ObjectId('6a05318b22afbaefbce24182'), ObjectId('6a05318b22afbaefbce24183'), ObjectId('6a05318b22afbaefbce24184'), ObjectId('6a05318b22afbaefbce24185'), ObjectId('6a05318b22afbaefbce24186'), ObjectId('6a05318b22afbaefbce24187'), ObjectId('6a05318b22afbaefbce24188'), ObjectId('6a05318b22afbaefbce24189'), ObjectId('6a05318b22afbaefbce2418a'), ObjectId('6a05318b22afbaefbce2418b'), ObjectId('6a05318b22afbaefbce2418c'), ObjectId('6a05318b22afbaefbce2418d'), ObjectId('6a05318b22afbaefbce2418e'), ObjectId('6a05318b22afbaefbce2418f'), ObjectId('6a05318b22afbaefbce24190'), ObjectId('6a05318b22afbaefbce24191'), ObjectId('6a05318b22afbaefbce24192'), ObjectId('6a05318b22afbaefbce24193'), ObjectId('6a05318b22afbaefbce24194'), ObjectId('6a05318b22afbaefbce24195'), ObjectId('6a05318b22afbaefbce24196'), ObjectId('6a05318b22afbaefbce24197'), ObjectId('6a05318b22afbaefbce24198'), ObjectId('6a05318b22afbaefbce24199'), ObjectId('6a05318b22afbaefbce2419a'), ObjectId('6a05318b22afbaefbce2419b'), ObjectId('6a05318b22afbaefbce2419c'), ObjectId('6a05318b22afbaefbce2419d'), ObjectId('6a05318b22afbaefbce2419e'), ObjectId('6a05318b22afbaefbce2419f'), ObjectId('6a05318b22afbaefbce241a0'), ObjectId('6a05318b22afbaefbce241a1'), ObjectId('6a05318b22afbaefbce241a2'), ObjectId('6a05318b22afbaefbce241a3'), ObjectId('6a05318b22afbaefbce241a4'), ObjectId('6a05318b22afbaefbce241a5'), ObjectId('6a05318b22afbaefbce241a6'), ObjectId('6a05318b22afbaefbce241a7'), ObjectId('6a05318b22afbaefbce241a8'), ObjectId('6a05318b22afbaefbce241a9'), ObjectId('6a05318b22afbaefbce241aa'), ObjectId('6a05318b22afbaefbce241ab'), ObjectId('6a05318b22afbaefbce241ac'), ObjectId('6a05318b22afbaefbce241ad'), ObjectId('6a05318b22afbaefbce241ae'), ObjectId('6a05318b22afbaefbce241af'), ObjectId('6a05318b22afbaefbce241b0'), ObjectId('6a05318b22afbaefbce241b1'), ObjectId('6a05318b22afbaefbce241b2'), ObjectId('6a05318b22afbaefbce241b3'), ObjectId('6a05318b22afbaefbce241b4'), ObjectId('6a05318b22afbaefbce241b5'), ObjectId('6a05318b22afbaefbce241b6'), ObjectId('6a05318b22afbaefbce241b7'), ObjectId('6a05318b22afbaefbce241b8'), ObjectId('6a05318b22afbaefbce241b9'), ObjectId('6a05318b22afbaefbce241ba'), ObjectId('6a05318b22afbaefbce241bb'), ObjectId('6a05318b22afbaefbce241bc'), ObjectId('6a05318b22afbaefbce241bd'), ObjectId('6a05318b22afbaefbce241be'), ObjectId('6a05318b22afbaefbce241bf'), ObjectId('6a05318b22afbaefbce241c0'), ObjectId('6a05318b22afbaefbce241c1'), ObjectId('6a05318b22afbaefbce241c2'), ObjectId('6a05318b22afbaefbce241c3'), ObjectId('6a05318b22afbaefbce241c4'), ObjectId('6a05318b22afbaefbce241c5'), ObjectId('6a05318b22afbaefbce241c6'), ObjectId('6a05318b22afbaefbce241c7'), ObjectId('6a05318b22afbaefbce241c8'), ObjectId('6a05318b22afbaefbce241c9'), ObjectId('6a05318b22afbaefbce241ca'), ObjectId('6a05318b22afbaefbce241cb'), ObjectId('6a05318b22afbaefbce241cc'), ObjectId('6a05318b22afbaefbce241cd'), ObjectId('6a05318b22afbaefbce241ce'), ObjectId('6a05318b22afbaefbce241cf'), ObjectId('6a05318b22afbaefbce241d0'), ObjectId('6a05318b22afbaefbce241d1'), ObjectId('6a05318b22afbaefbce241d2'), ObjectId('6a05318b22afbaefbce241d3'), ObjectId('6a05318b22afbaefbce241d4'), ObjectId('6a05318b22afbaefbce241d5'), ObjectId('6a05318b22afbaefbce241d6'), ObjectId('6a05318b22afbaefbce241d7'), ObjectId('6a05318b22afbaefbce241d8'), ObjectId('6a05318b22afbaefbce241d9'), ObjectId('6a05318b22afbaefbce241da'), ObjectId('6a05318b22afbaefbce241db'), ObjectId('6a05318b22afbaefbce241dc'), ObjectId('6a05318b22afbaefbce241dd'), ObjectId('6a05318b22afbaefbce241de'), ObjectId('6a05318b22afbaefbce241df'), ObjectId('6a05318b22afbaefbce241e0'), ObjectId('6a05318b22afbaefbce241e1'), ObjectId('6a05318b22afbaefbce241e2'), ObjectId('6a05318b22afbaefbce241e3'), ObjectId('6a05318b22afbaefbce241e4'), ObjectId('6a05318b22afbaefbce241e5'), ObjectId('6a05318b22afbaefbce241e6'), ObjectId('6a05318b22afbaefbce241e7'), ObjectId('6a05318b22afbaefbce241e8'), ObjectId('6a05318b22afbaefbce241e9'), ObjectId('6a05318b22afbaefbce241ea'), ObjectId('6a05318b22afbaefbce241eb'), ObjectId('6a05318b22afbaefbce241ec'), ObjectId('6a05318b22afbaefbce241ed'), ObjectId('6a05318b22afbaefbce241ee'), ObjectId('6a05318b22afbaefbce241ef'), ObjectId('6a05318b22afbaefbce241f0'), ObjectId('6a05318b22afbaefbce241f1'), ObjectId('6a05318b22afbaefbce241f2'), ObjectId('6a05318b22afbaefbce241f3'), ObjectId('6a05318b22afbaefbce241f4'), ObjectId('6a05318b22afbaefbce241f5'), ObjectId('6a05318b22afbaefbce241f6'), ObjectId('6a05318b22afbaefbce241f7'), ObjectId('6a05318b22afbaefbce241f8'), ObjectId('6a05318b22afbaefbce241f9'), ObjectId('6a05318b22afbaefbce241fa'), ObjectId('6a05318b22afbaefbce241fb'), ObjectId('6a05318b22afbaefbce241fc'), ObjectId('6a05318b22afbaefbce241fd'), ObjectId('6a05318b22afbaefbce241fe'), ObjectId('6a05318b22afbaefbce241ff'), ObjectId('6a05318b22afbaefbce24200'), ObjectId('6a05318b22afbaefbce24201'), ObjectId('6a05318b22afbaefbce24202'), ObjectId('6a05318b22afbaefbce24203'), ObjectId('6a05318b22afbaefbce24204'), ObjectId('6a05318b22afbaefbce24205'), ObjectId('6a05318b22afbaefbce24206'), ObjectId('6a05318b22afbaefbce24207'), ObjectId('6a05318b22afbaefbce24208'), ObjectId('6a05318b22afbaefbce24209'), ObjectId('6a05318b22afbaefbce2420a'), ObjectId('6a05318b22afbaefbce2420b'), ObjectId('6a05318b22afbaefbce2420c'), ObjectId('6a05318b22afbaefbce2420d'), ObjectId('6a05318b22afbaefbce2420e'), ObjectId('6a05318b22afbaefbce2420f'), ObjectId('6a05318b22afbaefbce24210'), ObjectId('6a05318b22afbaefbce24211'), ObjectId('6a05318b22afbaefbce24212'), ObjectId('6a05318b22afbaefbce24213'), ObjectId('6a05318b22afbaefbce24214'), ObjectId('6a05318b22afbaefbce24215'), ObjectId('6a05318b22afbaefbce24216'), ObjectId('6a05318b22afbaefbce24217'), ObjectId('6a05318b22afbaefbce24218'), ObjectId('6a05318b22afbaefbce24219'), ObjectId('6a05318b22afbaefbce2421a'), ObjectId('6a05318b22afbaefbce2421b'), ObjectId('6a05318b22afbaefbce2421c'), ObjectId('6a05318b22afbaefbce2421d'), ObjectId('6a05318b22afbaefbce2421e'), ObjectId('6a05318b22afbaefbce2421f'), ObjectId('6a05318b22afbaefbce24220'), ObjectId('6a05318b22afbaefbce24221'), ObjectId('6a05318b22afbaefbce24222'), ObjectId('6a05318b22afbaefbce24223'), ObjectId('6a05318b22afbaefbce24224'), ObjectId('6a05318b22afbaefbce24225'), ObjectId('6a05318b22afbaefbce24226'), ObjectId('6a05318b22afbaefbce24227'), ObjectId('6a05318b22afbaefbce24228'), ObjectId('6a05318b22afbaefbce24229'), ObjectId('6a05318b22afbaefbce2422a'), ObjectId('6a05318b22afbaefbce2422b'), ObjectId('6a05318b22afbaefbce2422c'), ObjectId('6a05318b22afbaefbce2422d'), ObjectId('6a05318b22afbaefbce2422e'), ObjectId('6a05318b22afbaefbce2422f'), ObjectId('6a05318b22afbaefbce24230'), ObjectId('6a05318b22afbaefbce24231'), ObjectId('6a05318b22afbaefbce24232'), ObjectId('6a05318b22afbaefbce24233'), ObjectId('6a05318b22afbaefbce24234'), ObjectId('6a05318b22afbaefbce24235'), ObjectId('6a05318b22afbaefbce24236'), ObjectId('6a05318b22afbaefbce24237'), ObjectId('6a05318b22afbaefbce24238'), ObjectId('6a05318b22afbaefbce24239'), ObjectId('6a05318b22afbaefbce2423a'), ObjectId('6a05318b22afbaefbce2423b'), ObjectId('6a05318b22afbaefbce2423c'), ObjectId('6a05318b22afbaefbce2423d'), ObjectId('6a05318b22afbaefbce2423e'), ObjectId('6a05318b22afbaefbce2423f'), ObjectId('6a05318b22afbaefbce24240'), ObjectId('6a05318b22afbaefbce24241'), ObjectId('6a05318b22afbaefbce24242'), ObjectId('6a05318b22afbaefbce24243'), ObjectId('6a05318b22afbaefbce24244'), ObjectId('6a05318b22afbaefbce24245'), ObjectId('6a05318b22afbaefbce24246'), ObjectId('6a05318b22afbaefbce24247'), ObjectId('6a05318b22afbaefbce24248'), ObjectId('6a05318b22afbaefbce24249'), ObjectId('6a05318b22afbaefbce2424a'), ObjectId('6a05318b22afbaefbce2424b'), ObjectId('6a05318b22afbaefbce2424c'), ObjectId('6a05318b22afbaefbce2424d'), ObjectId('6a05318b22afbaefbce2424e'), ObjectId('6a05318b22afbaefbce2424f'), ObjectId('6a05318b22afbaefbce24250'), ObjectId('6a05318b22afbaefbce24251'), ObjectId('6a05318b22afbaefbce24252'), ObjectId('6a05318b22afbaefbce24253'), ObjectId('6a05318b22afbaefbce24254'), ObjectId('6a05318b22afbaefbce24255'), ObjectId('6a05318b22afbaefbce24256'), ObjectId('6a05318b22afbaefbce24257'), ObjectId('6a05318b22afbaefbce24258'), ObjectId('6a05318b22afbaefbce24259'), ObjectId('6a05318b22afbaefbce2425a'), ObjectId('6a05318b22afbaefbce2425b'), ObjectId('6a05318b22afbaefbce2425c'), ObjectId('6a05318b22afbaefbce2425d'), ObjectId('6a05318b22afbaefbce2425e'), ObjectId('6a05318b22afbaefbce2425f'), ObjectId('6a05318b22afbaefbce24260'), ObjectId('6a05318b22afbaefbce24261'), ObjectId('6a05318b22afbaefbce24262'), ObjectId('6a05318b22afbaefbce24263'), ObjectId('6a05318b22afbaefbce24264'), ObjectId('6a05318b22afbaefbce24265'), ObjectId('6a05318b22afbaefbce24266'), ObjectId('6a05318b22afbaefbce24267'), ObjectId('6a05318b22afbaefbce24268'), ObjectId('6a05318b22afbaefbce24269'), ObjectId('6a05318b22afbaefbce2426a'), ObjectId('6a05318b22afbaefbce2426b'), ObjectId('6a05318b22afbaefbce2426c'), ObjectId('6a05318b22afbaefbce2426d'), ObjectId('6a05318b22afbaefbce2426e'), ObjectId('6a05318b22afbaefbce2426f'), ObjectId('6a05318b22afbaefbce24270'), ObjectId('6a05318b22afbaefbce24271'), ObjectId('6a05318b22afbaefbce24272'), ObjectId('6a05318b22afbaefbce24273'), ObjectId('6a05318b22afbaefbce24274'), ObjectId('6a05318b22afbaefbce24275'), ObjectId('6a05318b22afbaefbce24276'), ObjectId('6a05318b22afbaefbce24277'), ObjectId('6a05318b22afbaefbce24278'), ObjectId('6a05318b22afbaefbce24279'), ObjectId('6a05318b22afbaefbce2427a'), ObjectId('6a05318b22afbaefbce2427b'), ObjectId('6a05318b22afbaefbce2427c'), ObjectId('6a05318b22afbaefbce2427d'), ObjectId('6a05318b22afbaefbce2427e'), ObjectId('6a05318b22afbaefbce2427f'), ObjectId('6a05318b22afbaefbce24280'), ObjectId('6a05318b22afbaefbce24281'), ObjectId('6a05318b22afbaefbce24282'), ObjectId('6a05318b22afbaefbce24283'), ObjectId('6a05318b22afbaefbce24284'), ObjectId('6a05318b22afbaefbce24285'), ObjectId('6a05318b22afbaefbce24286'), ObjectId('6a05318b22afbaefbce24287'), ObjectId('6a05318b22afbaefbce24288'), ObjectId('6a05318b22afbaefbce24289'), ObjectId('6a05318b22afbaefbce2428a'), ObjectId('6a05318b22afbaefbce2428b'), ObjectId('6a05318b22afbaefbce2428c'), ObjectId('6a05318b22afbaefbce2428d'), ObjectId('6a05318b22afbaefbce2428e'), ObjectId('6a05318b22afbaefbce2428f'), ObjectId('6a05318b22afbaefbce24290'), ObjectId('6a05318b22afbaefbce24291'), ObjectId('6a05318b22afbaefbce24292'), ObjectId('6a05318b22afbaefbce24293'), ObjectId('6a05318b22afbaefbce24294'), ObjectId('6a05318b22afbaefbce24295'), ObjectId('6a05318b22afbaefbce24296'), ObjectId('6a05318b22afbaefbce24297'), ObjectId('6a05318b22afbaefbce24298'), ObjectId('6a05318b22afbaefbce24299'), ObjectId('6a05318b22afbaefbce2429a'), ObjectId('6a05318b22afbaefbce2429b'), ObjectId('6a05318b22afbaefbce2429c'), ObjectId('6a05318b22afbaefbce2429d'), ObjectId('6a05318b22afbaefbce2429e'), ObjectId('6a05318b22afbaefbce2429f'), ObjectId('6a05318b22afbaefbce242a0'), ObjectId('6a05318b22afbaefbce242a1'), ObjectId('6a05318b22afbaefbce242a2'), ObjectId('6a05318b22afbaefbce242a3'), ObjectId('6a05318b22afbaefbce242a4'), ObjectId('6a05318b22afbaefbce242a5'), ObjectId('6a05318b22afbaefbce242a6'), ObjectId('6a05318b22afbaefbce242a7'), ObjectId('6a05318b22afbaefbce242a8'), ObjectId('6a05318b22afbaefbce242a9'), ObjectId('6a05318b22afbaefbce242aa'), ObjectId('6a05318b22afbaefbce242ab'), ObjectId('6a05318b22afbaefbce242ac'), ObjectId('6a05318b22afbaefbce242ad'), ObjectId('6a05318b22afbaefbce242ae'), ObjectId('6a05318b22afbaefbce242af'), ObjectId('6a05318b22afbaefbce242b0'), ObjectId('6a05318b22afbaefbce242b1'), ObjectId('6a05318b22afbaefbce242b2'), ObjectId('6a05318b22afbaefbce242b3'), ObjectId('6a05318b22afbaefbce242b4'), ObjectId('6a05318b22afbaefbce242b5'), ObjectId('6a05318b22afbaefbce242b6'), ObjectId('6a05318b22afbaefbce242b7'), ObjectId('6a05318b22afbaefbce242b8'), ObjectId('6a05318b22afbaefbce242b9'), ObjectId('6a05318b22afbaefbce242ba'), ObjectId('6a05318b22afbaefbce242bb'), ObjectId('6a05318b22afbaefbce242bc'), ObjectId('6a05318b22afbaefbce242bd'), ObjectId('6a05318b22afbaefbce242be'), ObjectId('6a05318b22afbaefbce242bf'), ObjectId('6a05318b22afbaefbce242c0'), ObjectId('6a05318b22afbaefbce242c1'), ObjectId('6a05318b22afbaefbce242c2'), ObjectId('6a05318b22afbaefbce242c3'), ObjectId('6a05318b22afbaefbce242c4'), ObjectId('6a05318b22afbaefbce242c5'), ObjectId('6a05318b22afbaefbce242c6'), ObjectId('6a05318b22afbaefbce242c7'), ObjectId('6a05318b22afbaefbce242c8'), ObjectId('6a05318b22afbaefbce242c9'), ObjectId('6a05318b22afbaefbce242ca'), ObjectId('6a05318b22afbaefbce242cb'), ObjectId('6a05318b22afbaefbce242cc'), ObjectId('6a05318b22afbaefbce242cd'), ObjectId('6a05318b22afbaefbce242ce'), ObjectId('6a05318b22afbaefbce242cf'), ObjectId('6a05318b22afbaefbce242d0'), ObjectId('6a05318b22afbaefbce242d1'), ObjectId('6a05318b22afbaefbce242d2'), ObjectId('6a05318b22afbaefbce242d3'), ObjectId('6a05318b22afbaefbce242d4'), ObjectId('6a05318b22afbaefbce242d5'), ObjectId('6a05318b22afbaefbce242d6'), ObjectId('6a05318b22afbaefbce242d7'), ObjectId('6a05318b22afbaefbce242d8'), ObjectId('6a05318b22afbaefbce242d9'), ObjectId('6a05318b22afbaefbce242da'), ObjectId('6a05318b22afbaefbce242db'), ObjectId('6a05318b22afbaefbce242dc'), ObjectId('6a05318b22afbaefbce242dd'), ObjectId('6a05318b22afbaefbce242de'), ObjectId('6a05318b22afbaefbce242df'), ObjectId('6a05318b22afbaefbce242e0'), ObjectId('6a05318b22afbaefbce242e1'), ObjectId('6a05318b22afbaefbce242e2'), ObjectId('6a05318b22afbaefbce242e3'), ObjectId('6a05318b22afbaefbce242e4'), ObjectId('6a05318b22afbaefbce242e5'), ObjectId('6a05318b22afbaefbce242e6'), ObjectId('6a05318b22afbaefbce242e7'), ObjectId('6a05318b22afbaefbce242e8'), ObjectId('6a05318b22afbaefbce242e9'), ObjectId('6a05318b22afbaefbce242ea'), ObjectId('6a05318b22afbaefbce242eb'), ObjectId('6a05318b22afbaefbce242ec'), ObjectId('6a05318b22afbaefbce242ed'), ObjectId('6a05318b22afbaefbce242ee'), ObjectId('6a05318b22afbaefbce242ef'), ObjectId('6a05318b22afbaefbce242f0'), ObjectId('6a05318b22afbaefbce242f1'), ObjectId('6a05318b22afbaefbce242f2'), ObjectId('6a05318b22afbaefbce242f3'), ObjectId('6a05318b22afbaefbce242f4'), ObjectId('6a05318b22afbaefbce242f5'), ObjectId('6a05318b22afbaefbce242f6'), ObjectId('6a05318b22afbaefbce242f7'), ObjectId('6a05318b22afbaefbce242f8'), ObjectId('6a05318b22afbaefbce242f9'), ObjectId('6a05318b22afbaefbce242fa'), ObjectId('6a05318b22afbaefbce242fb'), ObjectId('6a05318b22afbaefbce242fc'), ObjectId('6a05318b22afbaefbce242fd'), ObjectId('6a05318b22afbaefbce242fe'), ObjectId('6a05318b22afbaefbce242ff'), ObjectId('6a05318b22afbaefbce24300'), ObjectId('6a05318b22afbaefbce24301'), ObjectId('6a05318b22afbaefbce24302'), ObjectId('6a05318b22afbaefbce24303'), ObjectId('6a05318b22afbaefbce24304'), ObjectId('6a05318b22afbaefbce24305'), ObjectId('6a05318b22afbaefbce24306'), ObjectId('6a05318b22afbaefbce24307'), ObjectId('6a05318b22afbaefbce24308'), ObjectId('6a05318b22afbaefbce243

---

In [ ]:
import pandas as pd

# 가져올 collection 선택
c1 = db.get_collection("customer_master")
c2 = db.get_collection("item_master")
c3 = db.get_collection("transaction_master")

# 전체 데이터를 가져오는데 _id정보는 제거해서
d1 = c1.find({}, {"_id": 0})
d2 = c2.find({}, {"_id": 0})
d3 = c3.find({}, {"_id": 0})

# 가져온 데이터를 DataFrame으로 변경
customer = pd.DataFrame(list(d1))
item = pd.DataFrame(list(d2))
transaction = pd.DataFrame(list(d3))

In [ ]:
# 5000명
customer.info()

In [ ]:
# 5개의 물품
item.info()

In [ ]:
# 6786개 거래내역
transaction.info()

In [24]:
transaction_d1 = pd.read_csv('http://114.207.245.181:13000/csv/transaction_detail_1.csv')
transaction_d2 = pd.read_csv('http://114.207.245.181:13000/csv/transaction_detail_2.csv')

transaction_detail = pd.concat([transaction_d1, transaction_d2], ignore_index=True)
transaction_detail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       7144 non-null   int64
 1   transaction_id  7144 non-null   object
 2   item_id         7144 non-null   object
 3   quantity        7144 non-null   int64
dtypes: int64(2), object(2)
memory usage: 223.4+ KB

In [33]:
transaction_detail.columns.to_list()

['detail_id', 'transaction_id', 'item_id', 'quantity']

In [34]:
d_for_rename = dict(zip(
    ['detail_id', 'transaction_id', 'item_id', 'quantity'],
    ["거래번호", "거래코드", "물품코드", "수량"]
))

In [36]:
transaction_detail = transaction_detail.rename(columns=d_for_rename)
transaction_detail

      거래번호         거래코드  물품코드  수량
0        0  T0000000113  S005   1
1        1  T0000000114  S001   1
2        2  T0000000115  S003   1
3        3  T0000000116  S005   1
4        4  T0000000117  S002   2
...    ...          ...   ...  ..
7139  7139  T0000006894  S004   1
7140  7140  T0000006895  S002   1
7141  7141  T0000006896  S001   2
7142  7142  T0000006897  S002   1
7143  7143  T0000006898  S002   1

[7144 rows x 4 columns]

In [ ]:
# transaction: 중국집에 54000, transaction_detail: 짜장1개, 짬뽕2 등
print(transaction.shape, transaction_detail.shape)

(6786, 4) (7144, 4)

In [39]:
# 거래코드가 중복인 항목 표시
foo = transaction_detail[transaction_detail['거래코드'].duplicated(keep=False)]
foo.shape

(697, 4)

In [42]:
sum(transaction['결제금액'])

971135000

In [43]:
transaction.head(3)

          거래코드    결제금액                결제일시     고객아이디
0  T0000000113  210000 2019-02-01 01:36:57  PL563502
1  T0000000114   50000 2019-02-01 01:37:23  HD678019
2  T0000000115  120000 2019-02-01 02:34:19  HD298120

In [45]:
transaction_detail.head(1)

   거래번호         거래코드  물품코드  수량
0     0  T0000000113  S005   1

In [47]:
transaction[['거래코드', '결제일시', '고객아이디']].head(1)

          거래코드                결제일시     고객아이디
0  T0000000113 2019-02-01 01:36:57  PL563502

In [48]:
transaction_detail[['거래코드', '물품코드', '수량']].head(1)

          거래코드  물품코드  수량
0  T0000000113  S005   1

In [51]:
transaction_data = pd.merge(
    transaction[['거래코드', '결제일시', '고객아이디']],
    transaction_detail[['거래코드', '물품코드', '수량']],
    on="거래코드",
    how="right"
)

transaction_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   거래코드    7144 non-null   object
 1   결제일시    7144 non-null   datetime64[ns]
 2   고객아이디   7144 non-null   object
 3   물품코드    7144 non-null   object
 4   수량      7144 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 279.2+ KB

In [55]:
transaction_data.head(3)

          거래코드                결제일시     고객아이디  물품코드  수량
0  T0000000113 2019-02-01 01:36:57  PL563502  S005   1
1  T0000000114 2019-02-01 01:37:23  HD678019  S001   1
2  T0000000115 2019-02-01 02:34:19  HD298120  S003   1

In [62]:
item

   물품코드   물품명    물품가격
0  S001  PC-A   50000
1  S002  PC-B   85000
2  S003  PC-C  120000
3  S004  PC-D  180000
4  S005  PC-E  210000

In [64]:
customer.shape

(5000, 12)

In [60]:
transaction_item_data = pd.merge(
    transaction_data,
    item,
    left_on="물품코드",
    right_on="물품코드",
    how="left"
)
transaction_item_data

             거래코드                결제일시     고객아이디  물품코드  수량   물품명    물품가격
0     T0000000113 2019-02-01 01:36:57  PL563502  S005   1  PC-E  210000
1     T0000000114 2019-02-01 01:37:23  HD678019  S001   1  PC-A   50000
2     T0000000115 2019-02-01 02:34:19  HD298120  S003   1  PC-C  120000
3     T0000000116 2019-02-01 02:47:23  IK452215  S005   1  PC-E  210000
4     T0000000117 2019-02-01 04:33:46  PL542865  S002   2  PC-B   85000
...           ...                 ...       ...   ...  ..   ...     ...
7139  T0000006894 2019-07-31 21:20:44  HI400734  S004   1  PC-D  180000
7140  T0000006895 2019-07-31 21:52:48  AS339451  S002   1  PC-B   85000
7141  T0000006896 2019-07-31 23:35:25  OA027325  S001   2  PC-A   50000
7142  T0000006897 2019-07-31 23:39:35  TS624738  S002   1  PC-B   85000
7143  T0000006898 2019-07-31 23:41:38  AS834214  S002   1  PC-B   85000

[7144 rows x 7 columns]

In [65]:
customer.head(1)

,고객아이디,고객명,등록일시,이메일,성별,나이,생년월일,지역,년,월,일,연령대
0,IK152942,김서준,2019-01-01 00:25:00,hirata_yuujirou@example.com,M,37,1990-06-10,대전광역시,1990,6,10,30대

In [69]:
data =pd.merge(
    transaction_item_data,
    customer,
    on="고객아이디",
    how="left"
)
print(data.shape)
data.head(3)

(7144, 18)

,거래코드,결제일시,고객아이디,물품코드,수량,물품명,물품가격,고객명,등록일시,이메일,성별,나이,생년월일,지역,년,월,일,연령대
0,T0000000113,2019-02-01 01:36:57,PL563502,S005,1,PC-E,210000,김태경,2019-01-07 14:34:00,imoto_yoshimasa@example.com,M,38,1989-07-15,대전광역시,1989,7,15,30대
1,T0000000114,2019-02-01 01:37:23,HD678019,S001,1,PC-A,50000,김영웅,2019-01-27 18:00:00,mifune_rokurou@example.com,M,82,1945-11-29,서울특별시,1945,11,29,80이상
2,T0000000115,2019-02-01 02:34:19,HD298120,S003,1,PC-C,120000,김강현,2019-01-11 08:16:00,yamane_kogan@example.com,M,50,1977-05-17,광주광역시,1977,5,17,50대

In [ ]:
# 거래금액 생성
data['거래금액'] = data['수량'] * data['물품가격']

In [71]:
sum(data['거래금액'])

971135000

In [ ]:
data.to_pickle('./pkl/data.pkl')

In [75]:
col_data = db.get_collection("data_master")
data_t = data.to_dict(orient="records")
col_data.insert_many(data_t)

InsertManyResult([ObjectId('6a05694422afbaefbce25b7e'), ObjectId('6a05694422afbaefbce25b7f'), ObjectId('6a05694422afbaefbce25b80'), ObjectId('6a05694422afbaefbce25b81'), ObjectId('6a05694422afbaefbce25b82'), ObjectId('6a05694422afbaefbce25b83'), ObjectId('6a05694422afbaefbce25b84'), ObjectId('6a05694422afbaefbce25b85'), ObjectId('6a05694422afbaefbce25b86'), ObjectId('6a05694422afbaefbce25b87'), ObjectId('6a05694422afbaefbce25b88'), ObjectId('6a05694422afbaefbce25b89'), ObjectId('6a05694422afbaefbce25b8a'), ObjectId('6a05694422afbaefbce25b8b'), ObjectId('6a05694422afbaefbce25b8c'), ObjectId('6a05694422afbaefbce25b8d'), ObjectId('6a05694422afbaefbce25b8e'), ObjectId('6a05694422afbaefbce25b8f'), ObjectId('6a05694422afbaefbce25b90'), ObjectId('6a05694422afbaefbce25b91'), ObjectId('6a05694422afbaefbce25b92'), ObjectId('6a05694422afbaefbce25b93'), ObjectId('6a05694422afbaefbce25b94'), ObjectId('6a05694422afbaefbce25b95'), ObjectId('6a05694422afbaefbce25b96'), ObjectId('6a05694422afbaefbce25b97'), ObjectId('6a05694422afbaefbce25b98'), ObjectId('6a05694422afbaefbce25b99'), ObjectId('6a05694422afbaefbce25b9a'), ObjectId('6a05694422afbaefbce25b9b'), ObjectId('6a05694422afbaefbce25b9c'), ObjectId('6a05694422afbaefbce25b9d'), ObjectId('6a05694422afbaefbce25b9e'), ObjectId('6a05694422afbaefbce25b9f'), ObjectId('6a05694422afbaefbce25ba0'), ObjectId('6a05694422afbaefbce25ba1'), ObjectId('6a05694422afbaefbce25ba2'), ObjectId('6a05694422afbaefbce25ba3'), ObjectId('6a05694422afbaefbce25ba4'), ObjectId('6a05694422afbaefbce25ba5'), ObjectId('6a05694422afbaefbce25ba6'), ObjectId('6a05694422afbaefbce25ba7'), ObjectId('6a05694422afbaefbce25ba8'), ObjectId('6a05694422afbaefbce25ba9'), ObjectId('6a05694422afbaefbce25baa'), ObjectId('6a05694422afbaefbce25bab'), ObjectId('6a05694422afbaefbce25bac'), ObjectId('6a05694422afbaefbce25bad'), ObjectId('6a05694422afbaefbce25bae'), ObjectId('6a05694422afbaefbce25baf'), ObjectId('6a05694422afbaefbce25bb0'), ObjectId('6a05694422afbaefbce25bb1'), ObjectId('6a05694422afbaefbce25bb2'), ObjectId('6a05694422afbaefbce25bb3'), ObjectId('6a05694422afbaefbce25bb4'), ObjectId('6a05694422afbaefbce25bb5'), ObjectId('6a05694422afbaefbce25bb6'), ObjectId('6a05694422afbaefbce25bb7'), ObjectId('6a05694422afbaefbce25bb8'), ObjectId('6a05694422afbaefbce25bb9'), ObjectId('6a05694422afbaefbce25bba'), ObjectId('6a05694422afbaefbce25bbb'), ObjectId('6a05694422afbaefbce25bbc'), ObjectId('6a05694422afbaefbce25bbd'), ObjectId('6a05694422afbaefbce25bbe'), ObjectId('6a05694422afbaefbce25bbf'), ObjectId('6a05694422afbaefbce25bc0'), ObjectId('6a05694422afbaefbce25bc1'), ObjectId('6a05694422afbaefbce25bc2'), ObjectId('6a05694422afbaefbce25bc3'), ObjectId('6a05694422afbaefbce25bc4'), ObjectId('6a05694422afbaefbce25bc5'), ObjectId('6a05694422afbaefbce25bc6'), ObjectId('6a05694422afbaefbce25bc7'), ObjectId('6a05694422afbaefbce25bc8'), ObjectId('6a05694422afbaefbce25bc9'), ObjectId('6a05694422afbaefbce25bca'), ObjectId('6a05694422afbaefbce25bcb'), ObjectId('6a05694422afbaefbce25bcc'), ObjectId('6a05694422afbaefbce25bcd'), ObjectId('6a05694422afbaefbce25bce'), ObjectId('6a05694422afbaefbce25bcf'), ObjectId('6a05694422afbaefbce25bd0'), ObjectId('6a05694422afbaefbce25bd1'), ObjectId('6a05694422afbaefbce25bd2'), ObjectId('6a05694422afbaefbce25bd3'), ObjectId('6a05694422afbaefbce25bd4'), ObjectId('6a05694422afbaefbce25bd5'), ObjectId('6a05694422afbaefbce25bd6'), ObjectId('6a05694422afbaefbce25bd7'), ObjectId('6a05694422afbaefbce25bd8'), ObjectId('6a05694422afbaefbce25bd9'), ObjectId('6a05694422afbaefbce25bda'), ObjectId('6a05694422afbaefbce25bdb'), ObjectId('6a05694422afbaefbce25bdc'), ObjectId('6a05694422afbaefbce25bdd'), ObjectId('6a05694422afbaefbce25bde'), ObjectId('6a05694422afbaefbce25bdf'), ObjectId('6a05694422afbaefbce25be0'), ObjectId('6a05694422afbaefbce25be1'), ObjectId('6a05694422afbaefbce25be2'), ObjectId('6a05694422afbaefbce25be3'), ObjectId('6a05694422afbaefbce25be4'), ObjectId('6a05694422afbaefbce25be5'), ObjectId('6a05694422afbaefbce25be6'), ObjectId('6a05694422afbaefbce25be7'), ObjectId('6a05694422afbaefbce25be8'), ObjectId('6a05694422afbaefbce25be9'), ObjectId('6a05694422afbaefbce25bea'), ObjectId('6a05694422afbaefbce25beb'), ObjectId('6a05694422afbaefbce25bec'), ObjectId('6a05694422afbaefbce25bed'), ObjectId('6a05694422afbaefbce25bee'), ObjectId('6a05694422afbaefbce25bef'), ObjectId('6a05694422afbaefbce25bf0'), ObjectId('6a05694422afbaefbce25bf1'), ObjectId('6a05694422afbaefbce25bf2'), ObjectId('6a05694422afbaefbce25bf3'), ObjectId('6a05694422afbaefbce25bf4'), ObjectId('6a05694422afbaefbce25bf5'), ObjectId('6a05694422afbaefbce25bf6'), ObjectId('6a05694422afbaefbce25bf7'), ObjectId('6a05694422afbaefbce25bf8'), ObjectId('6a05694422afbaefbce25bf9'), ObjectId('6a05694422afbaefbce25bfa'), ObjectId('6a05694422afbaefbce25bfb'), ObjectId('6a05694422afbaefbce25bfc'), ObjectId('6a05694422afbaefbce25bfd'), ObjectId('6a05694422afbaefbce25bfe'), ObjectId('6a05694422afbaefbce25bff'), ObjectId('6a05694422afbaefbce25c00'), ObjectId('6a05694422afbaefbce25c01'), ObjectId('6a05694422afbaefbce25c02'), ObjectId('6a05694422afbaefbce25c03'), ObjectId('6a05694422afbaefbce25c04'), ObjectId('6a05694422afbaefbce25c05'), ObjectId('6a05694422afbaefbce25c06'), ObjectId('6a05694422afbaefbce25c07'), ObjectId('6a05694422afbaefbce25c08'), ObjectId('6a05694422afbaefbce25c09'), ObjectId('6a05694422afbaefbce25c0a'), ObjectId('6a05694422afbaefbce25c0b'), ObjectId('6a05694422afbaefbce25c0c'), ObjectId('6a05694422afbaefbce25c0d'), ObjectId('6a05694422afbaefbce25c0e'), ObjectId('6a05694422afbaefbce25c0f'), ObjectId('6a05694422afbaefbce25c10'), ObjectId('6a05694422afbaefbce25c11'), ObjectId('6a05694422afbaefbce25c12'), ObjectId('6a05694422afbaefbce25c13'), ObjectId('6a05694422afbaefbce25c14'), ObjectId('6a05694422afbaefbce25c15'), ObjectId('6a05694422afbaefbce25c16'), ObjectId('6a05694422afbaefbce25c17'), ObjectId('6a05694422afbaefbce25c18'), ObjectId('6a05694422afbaefbce25c19'), ObjectId('6a05694422afbaefbce25c1a'), ObjectId('6a05694422afbaefbce25c1b'), ObjectId('6a05694422afbaefbce25c1c'), ObjectId('6a05694422afbaefbce25c1d'), ObjectId('6a05694422afbaefbce25c1e'), ObjectId('6a05694422afbaefbce25c1f'), ObjectId('6a05694422afbaefbce25c20'), ObjectId('6a05694422afbaefbce25c21'), ObjectId('6a05694422afbaefbce25c22'), ObjectId('6a05694422afbaefbce25c23'), ObjectId('6a05694422afbaefbce25c24'), ObjectId('6a05694422afbaefbce25c25'), ObjectId('6a05694422afbaefbce25c26'), ObjectId('6a05694422afbaefbce25c27'), ObjectId('6a05694422afbaefbce25c28'), ObjectId('6a05694422afbaefbce25c29'), ObjectId('6a05694422afbaefbce25c2a'), ObjectId('6a05694422afbaefbce25c2b'), ObjectId('6a05694422afbaefbce25c2c'), ObjectId('6a05694422afbaefbce25c2d'), ObjectId('6a05694422afbaefbce25c2e'), ObjectId('6a05694422afbaefbce25c2f'), ObjectId('6a05694422afbaefbce25c30'), ObjectId('6a05694422afbaefbce25c31'), ObjectId('6a05694422afbaefbce25c32'), ObjectId('6a05694422afbaefbce25c33'), ObjectId('6a05694422afbaefbce25c34'), ObjectId('6a05694422afbaefbce25c35'), ObjectId('6a05694422afbaefbce25c36'), ObjectId('6a05694422afbaefbce25c37'), ObjectId('6a05694422afbaefbce25c38'), ObjectId('6a05694422afbaefbce25c39'), ObjectId('6a05694422afbaefbce25c3a'), ObjectId('6a05694422afbaefbce25c3b'), ObjectId('6a05694422afbaefbce25c3c'), ObjectId('6a05694422afbaefbce25c3d'), ObjectId('6a05694422afbaefbce25c3e'), ObjectId('6a05694422afbaefbce25c3f'), ObjectId('6a05694422afbaefbce25c40'), ObjectId('6a05694422afbaefbce25c41'), ObjectId('6a05694422afbaefbce25c42'), ObjectId('6a05694422afbaefbce25c43'), ObjectId('6a05694422afbaefbce25c44'), ObjectId('6a05694422afbaefbce25c45'), ObjectId('6a05694422afbaefbce25c46'), ObjectId('6a05694422afbaefbce25c47'), ObjectId('6a05694422afbaefbce25c48'), ObjectId('6a05694422afbaefbce25c49'), ObjectId('6a05694422afbaefbce25c4a'), ObjectId('6a05694422afbaefbce25c4b'), ObjectId('6a05694422afbaefbce25c4c'), ObjectId('6a05694422afbaefbce25c4d'), ObjectId('6a05694422afbaefbce25c4e'), ObjectId('6a05694422afbaefbce25c4f'), ObjectId('6a05694422afbaefbce25c50'), ObjectId('6a05694422afbaefbce25c51'), ObjectId('6a05694422afbaefbce25c52'), ObjectId('6a05694422afbaefbce25c53'), ObjectId('6a05694422afbaefbce25c54'), ObjectId('6a05694422afbaefbce25c55'), ObjectId('6a05694422afbaefbce25c56'), ObjectId('6a05694422afbaefbce25c57'), ObjectId('6a05694422afbaefbce25c58'), ObjectId('6a05694422afbaefbce25c59'), ObjectId('6a05694422afbaefbce25c5a'), ObjectId('6a05694422afbaefbce25c5b'), ObjectId('6a05694422afbaefbce25c5c'), ObjectId('6a05694422afbaefbce25c5d'), ObjectId('6a05694422afbaefbce25c5e'), ObjectId('6a05694422afbaefbce25c5f'), ObjectId('6a05694422afbaefbce25c60'), ObjectId('6a05694422afbaefbce25c61'), ObjectId('6a05694422afbaefbce25c62'), ObjectId('6a05694422afbaefbce25c63'), ObjectId('6a05694422afbaefbce25c64'), ObjectId('6a05694422afbaefbce25c65'), ObjectId('6a05694422afbaefbce25c66'), ObjectId('6a05694422afbaefbce25c67'), ObjectId('6a05694422afbaefbce25c68'), ObjectId('6a05694422afbaefbce25c69'), ObjectId('6a05694422afbaefbce25c6a'), ObjectId('6a05694422afbaefbce25c6b'), ObjectId('6a05694422afbaefbce25c6c'), ObjectId('6a05694422afbaefbce25c6d'), ObjectId('6a05694422afbaefbce25c6e'), ObjectId('6a05694422afbaefbce25c6f'), ObjectId('6a05694422afbaefbce25c70'), ObjectId('6a05694422afbaefbce25c71'), ObjectId('6a05694422afbaefbce25c72'), ObjectId('6a05694422afbaefbce25c73'), ObjectId('6a05694422afbaefbce25c74'), ObjectId('6a05694422afbaefbce25c75'), ObjectId('6a05694422afbaefbce25c76'), ObjectId('6a05694422afbaefbce25c77'), ObjectId('6a05694422afbaefbce25c78'), ObjectId('6a05694422afbaefbce25c79'), ObjectId('6a05694422afbaefbce25c7a'), ObjectId('6a05694422afbaefbce25c7b'), ObjectId('6a05694422afbaefbce25c7c'), ObjectId('6a05694422afbaefbce25c7d'), ObjectId('6a05694422afbaefbce25c7e'), ObjectId('6a05694422afbaefbce25c7f'), ObjectId('6a05694422afbaefbce25c80'), ObjectId('6a05694422afbaefbce25c81'), ObjectId('6a05694422afbaefbce25c82'), ObjectId('6a05694422afbaefbce25c83'), ObjectId('6a05694422afbaefbce25c84'), ObjectId('6a05694422afbaefbce25c85'), ObjectId('6a05694422afbaefbce25c86'), ObjectId('6a05694422afbaefbce25c87'), ObjectId('6a05694422afbaefbce25c88'), ObjectId('6a05694422afbaefbce25c89'), ObjectId('6a05694422afbaefbce25c8a'), ObjectId('6a05694422afbaefbce25c8b'), ObjectId('6a05694422afbaefbce25c8c'), ObjectId('6a05694422afbaefbce25c8d'), ObjectId('6a05694422afbaefbce25c8e'), ObjectId('6a05694422afbaefbce25c8f'), ObjectId('6a05694422afbaefbce25c90'), ObjectId('6a05694422afbaefbce25c91'), ObjectId('6a05694422afbaefbce25c92'), ObjectId('6a05694422afbaefbce25c93'), ObjectId('6a05694422afbaefbce25c94'), ObjectId('6a05694422afbaefbce25c95'), ObjectId('6a05694422afbaefbce25c96'), ObjectId('6a05694422afbaefbce25c97'), ObjectId('6a05694422afbaefbce25c98'), ObjectId('6a05694422afbaefbce25c99'), ObjectId('6a05694422afbaefbce25c9a'), ObjectId('6a05694422afbaefbce25c9b'), ObjectId('6a05694422afbaefbce25c9c'), ObjectId('6a05694422afbaefbce25c9d'), ObjectId('6a05694422afbaefbce25c9e'), ObjectId('6a05694422afbaefbce25c9f'), ObjectId('6a05694422afbaefbce25ca0'), ObjectId('6a05694422afbaefbce25ca1'), ObjectId('6a05694422afbaefbce25ca2'), ObjectId('6a05694422afbaefbce25ca3'), ObjectId('6a05694422afbaefbce25ca4'), ObjectId('6a05694422afbaefbce25ca5'), ObjectId('6a05694422afbaefbce25ca6'), ObjectId('6a05694422afbaefbce25ca7'), ObjectId('6a05694422afbaefbce25ca8'), ObjectId('6a05694422afbaefbce25ca9'), ObjectId('6a05694422afbaefbce25caa'), ObjectId('6a05694422afbaefbce25cab'), ObjectId('6a05694422afbaefbce25cac'), ObjectId('6a05694422afbaefbce25cad'), ObjectId('6a05694422afbaefbce25cae'), ObjectId('6a05694422afbaefbce25caf'), ObjectId('6a05694422afbaefbce25cb0'), ObjectId('6a05694422afbaefbce25cb1'), ObjectId('6a05694422afbaefbce25cb2'), ObjectId('6a05694422afbaefbce25cb3'), ObjectId('6a05694422afbaefbce25cb4'), ObjectId('6a05694422afbaefbce25cb5'), ObjectId('6a05694422afbaefbce25cb6'), ObjectId('6a05694422afbaefbce25cb7'), ObjectId('6a05694422afbaefbce25cb8'), ObjectId('6a05694422afbaefbce25cb9'), ObjectId('6a05694422afbaefbce25cba'), ObjectId('6a05694422afbaefbce25cbb'), ObjectId('6a05694422afbaefbce25cbc'), ObjectId('6a05694422afbaefbce25cbd'), ObjectId('6a05694422afbaefbce25cbe'), ObjectId('6a05694422afbaefbce25cbf'), ObjectId('6a05694422afbaefbce25cc0'), ObjectId('6a05694422afbaefbce25cc1'), ObjectId('6a05694422afbaefbce25cc2'), ObjectId('6a05694422afbaefbce25cc3'), ObjectId('6a05694422afbaefbce25cc4'), ObjectId('6a05694422afbaefbce25cc5'), ObjectId('6a05694422afbaefbce25cc6'), ObjectId('6a05694422afbaefbce25cc7'), ObjectId('6a05694422afbaefbce25cc8'), ObjectId('6a05694422afbaefbce25cc9'), ObjectId('6a05694422afbaefbce25cca'), ObjectId('6a05694422afbaefbce25ccb'), ObjectId('6a05694422afbaefbce25ccc'), ObjectId('6a05694422afbaefbce25ccd'), ObjectId('6a05694422afbaefbce25cce'), ObjectId('6a05694422afbaefbce25ccf'), ObjectId('6a05694422afbaefbce25cd0'), ObjectId('6a05694422afbaefbce25cd1'), ObjectId('6a05694422afbaefbce25cd2'), ObjectId('6a05694422afbaefbce25cd3'), ObjectId('6a05694422afbaefbce25cd4'), ObjectId('6a05694422afbaefbce25cd5'), ObjectId('6a05694422afbaefbce25cd6'), ObjectId('6a05694422afbaefbce25cd7'), ObjectId('6a05694422afbaefbce25cd8'), ObjectId('6a05694422afbaefbce25cd9'), ObjectId('6a05694422afbaefbce25cda'), ObjectId('6a05694422afbaefbce25cdb'), ObjectId('6a05694422afbaefbce25cdc'), ObjectId('6a05694422afbaefbce25cdd'), ObjectId('6a05694422afbaefbce25cde'), ObjectId('6a05694422afbaefbce25cdf'), ObjectId('6a05694422afbaefbce25ce0'), ObjectId('6a05694422afbaefbce25ce1'), ObjectId('6a05694422afbaefbce25ce2'), ObjectId('6a05694422afbaefbce25ce3'), ObjectId('6a05694422afbaefbce25ce4'), ObjectId('6a05694422afbaefbce25ce5'), ObjectId('6a05694422afbaefbce25ce6'), ObjectId('6a05694422afbaefbce25ce7'), ObjectId('6a05694422afbaefbce25ce8'), ObjectId('6a05694422afbaefbce25ce9'), ObjectId('6a05694422afbaefbce25cea'), ObjectId('6a05694422afbaefbce25ceb'), ObjectId('6a05694422afbaefbce25cec'), ObjectId('6a05694422afbaefbce25ced'), ObjectId('6a05694422afbaefbce25cee'), ObjectId('6a05694422afbaefbce25cef'), ObjectId('6a05694422afbaefbce25cf0'), ObjectId('6a05694422afbaefbce25cf1'), ObjectId('6a05694422afbaefbce25cf2'), ObjectId('6a05694422afbaefbce25cf3'), ObjectId('6a05694422afbaefbce25cf4'), ObjectId('6a05694422afbaefbce25cf5'), ObjectId('6a05694422afbaefbce25cf6'), ObjectId('6a05694422afbaefbce25cf7'), ObjectId('6a05694422afbaefbce25cf8'), ObjectId('6a05694422afbaefbce25cf9'), ObjectId('6a05694422afbaefbce25cfa'), ObjectId('6a05694422afbaefbce25cfb'), ObjectId('6a05694422afbaefbce25cfc'), ObjectId('6a05694422afbaefbce25cfd'), ObjectId('6a05694422afbaefbce25cfe'), ObjectId('6a05694422afbaefbce25cff'), ObjectId('6a05694422afbaefbce25d00'), ObjectId('6a05694422afbaefbce25d01'), ObjectId('6a05694422afbaefbce25d02'), ObjectId('6a05694422afbaefbce25d03'), ObjectId('6a05694422afbaefbce25d04'), ObjectId('6a05694422afbaefbce25d05'), ObjectId('6a05694422afbaefbce25d06'), ObjectId('6a05694422afbaefbce25d07'), ObjectId('6a05694422afbaefbce25d08'), ObjectId('6a05694422afbaefbce25d09'), ObjectId('6a05694422afbaefbce25d0a'), ObjectId('6a05694422afbaefbce25d0b'), ObjectId('6a05694422afbaefbce25d0c'), ObjectId('6a05694422afbaefbce25d0d'), ObjectId('6a05694422afbaefbce25d0e'), ObjectId('6a05694422afbaefbce25d0f'), ObjectId('6a05694422afbaefbce25d10'), ObjectId('6a05694422afbaefbce25d11'), ObjectId('6a05694422afbaefbce25d12'), ObjectId('6a05694422afbaefbce25d13'), ObjectId('6a05694422afbaefbce25d14'), ObjectId('6a05694422afbaefbce25d15'), ObjectId('6a05694422afbaefbce25d16'), ObjectId('6a05694422afbaefbce25d17'), ObjectId('6a05694422afbaefbce25d18'), ObjectId('6a05694422afbaefbce25d19'), ObjectId('6a05694422afbaefbce25d1a'), ObjectId('6a05694422afbaefbce25d1b'), ObjectId('6a05694422afbaefbce25d1c'), ObjectId('6a05694422afbaefbce25d1d'), ObjectId('6a05694422afbaefbce25d1e'), ObjectId('6a05694422afbaefbce25d1f'), ObjectId('6a05694422afbaefbce25d20'), ObjectId('6a05694422afbaefbce25d21'), ObjectId('6a05694422afbaefbce25d22'), ObjectId('6a05694422afbaefbce25d23'), ObjectId('6a05694422afbaefbce25d24'), ObjectId('6a05694422afbaefbce25d25'), ObjectId('6a05694422afbaefbce25d26'), ObjectId('6a05694422afbaefbce25d27'), ObjectId('6a05694422afbaefbce25d28'), ObjectId('6a05694422afbaefbce25d29'), ObjectId('6a05694422afbaefbce25d2a'), ObjectId('6a05694422afbaefbce25d2b'), ObjectId('6a05694422afbaefbce25d2c'), ObjectId('6a05694422afbaefbce25d2d'), ObjectId('6a05694422afbaefbce25d2e'), ObjectId('6a05694422afbaefbce25d2f'), ObjectId('6a05694422afbaefbce25d30'), ObjectId('6a05694422afbaefbce25d31'), ObjectId('6a05694422afbaefbce25d32'), ObjectId('6a05694422afbaefbce25d33'), ObjectId('6a05694422afbaefbce25d34'), ObjectId('6a05694422afbaefbce25d35'), ObjectId('6a05694422afbaefbce25d36'), ObjectId('6a05694422afbaefbce25d37'), ObjectId('6a05694422afbaefbce25d38'), ObjectId('6a05694422afbaefbce25d39'), ObjectId('6a05694422afbaefbce25d3a'), ObjectId('6a05694422afbaefbce25d3b'), ObjectId('6a05694422afbaefbce25d3c'), ObjectId('6a05694422afbaefbce25d3d'), ObjectId('6a05694422afbaefbce25d3e'), ObjectId('6a05694422afbaefbce25d3f'), ObjectId('6a05694422afbaefbce25d40'), ObjectId('6a05694422afbaefbce25d41'), ObjectId('6a05694422afbaefbce25d42'), ObjectId('6a05694422afbaefbce25d43'), ObjectId('6a05694422afbaefbce25d44'), ObjectId('6a05694422afbaefbce25d45'), ObjectId('6a05694422afbaefbce25d46'), ObjectId('6a05694422afbaefbce25d47'), ObjectId('6a05694422afbaefbce25d48'), ObjectId('6a05694422afbaefbce25d49'), ObjectId('6a05694422afbaefbce25d4a'), ObjectId('6a05694422afbaefbce25d4b'), ObjectId('6a05694422afbaefbce25d4c'), ObjectId('6a05694422afbaefbce25d4d'), ObjectId('6a05694422afbaefbce25d4e'), ObjectId('6a05694422afbaefbce25d4f'), ObjectId('6a05694422afbaefbce25d50'), ObjectId('6a05694422afbaefbce25d51'), ObjectId('6a05694422afbaefbce25d52'), ObjectId('6a05694422afbaefbce25d53'), ObjectId('6a05694422afbaefbce25d54'), ObjectId('6a05694422afbaefbce25d55'), ObjectId('6a05694422afbaefbce25d56'), ObjectId('6a05694422afbaefbce25d57'), ObjectId('6a05694422afbaefbce25d58'), ObjectId('6a05694422afbaefbce25d59'), ObjectId('6a05694422afbaefbce25d5a'), ObjectId('6a05694422afbaefbce25d5b'), ObjectId('6a05694422afbaefbce25d5c'), ObjectId('6a05694422afbaefbce25d5d'), ObjectId('6a05694422afbaefbce25d5e'), ObjectId('6a05694422afbaefbce25d5f'), ObjectId('6a05694422afbaefbce25d60'), ObjectId('6a05694422afbaefbce25d61'), ObjectId('6a05694422afbaefbce25d62'), ObjectId('6a05694422afbaefbce25d63'), ObjectId('6a05694422afbaefbce25d64'), ObjectId('6a05694422afbaefbce25d65'), ObjectId('6a05694422afbaefbce25d66'), ObjectId('6a05694422afbaefbce25d67'), ObjectId('6a05694422afbaefbce25d68'), ObjectId('6a05694422afbaefbce25d69'), ObjectId('6a05694422afbaefbce25d6a'), ObjectId('6a05694422afbaefbce25d6b'), ObjectId('6a05694422afbaefbce25d6c'), ObjectId('6a05694422afbaefbce25d6d'), ObjectId('6a05694422afbaefbce25d6e'), ObjectId('6a05694422afbaefbce25d6f'), ObjectId('6a05694422afbaefbce25d70'), ObjectId('6a05694422afbaefbce25d71'), ObjectId('6a05694422afbaefbce25d72'), ObjectId('6a05694422afbaefbce25d73'), ObjectId('6a05694422afbaefbce25d74'), ObjectId('6a05694422afbaefbce25d75'), ObjectId('6a05694422afbaefbce25d76'), ObjectId('6a05694422afbaefbce25d77'), ObjectId('6a05694422afbaefbce25d78'), ObjectId('6a05694422afbaefbce25d79'), ObjectId('6a05694422afbaefbce25d7a'), ObjectId('6a05694422afbaefbce25d7b'), ObjectId('6a05694422afbaefbce25d7c'), ObjectId('6a05694422afbaefbce25d7d'), ObjectId('6a05694422afbaefbce25d7e'), ObjectId('6a05694422afbaefbce25d7f'), ObjectId('6a05694422afbaefbce25d80'), ObjectId('6a05694422afbaefbce25d81'), ObjectId('6a05694422afbaefbce25d82'), ObjectId('6a05694422afbaefbce25d83'), ObjectId('6a05694422afbaefbce25d84'), ObjectId('6a05694422afbaefbce25d85'), ObjectId('6a05694422afbaefbce25d86'), ObjectId('6a05694422afbaefbce25d87'), ObjectId('6a05694422afbaefbce25d88'), ObjectId('6a05694422afbaefbce25d89'), ObjectId('6a05694422afbaefbce25d8a'), ObjectId('6a05694422afbaefbce25d